/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jdplus.tramoseats.desktop.plugin.tramo.ui;

import jdplus.toolkit.base.api.timeseries.Ts;
import jdplus.toolkit.base.api.timeseries.TsDomain;
import jdplus.tramoseats.desktop.plugin.tramo.documents.TramoDocumentManager;
import jdplus.tramoseats.base.core.tramo.TramoDocument;
import jdplus.toolkit.desktop.plugin.ui.processing.TsProcessingViewer;
import jdplus.toolkit.desktop.plugin.ui.properties.l2fprod.UserInterfaceContext;
import jdplus.toolkit.desktop.plugin.workspace.DocumentUIServices;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceFactory;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceItem;
import jdplus.toolkit.desktop.plugin.workspace.ui.WorkspaceTsTopComponent;
import jdplus.tramoseats.base.api.tramo.TramoSpec;
import nbbrd.design.ClassNameConstant;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.NbBundle;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//demetra.desktop.tramo.ui//Tramo//EN",
        autostore = false)
@TopComponent.Description(preferredID = "TramoTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Modelling", id = TramoTopComponent.ID)
@ActionReference(path = "Menu/Statistical methods/Modelling/Single Analysis", position = 1000)
@TopComponent.OpenActionRegistration(displayName = "#CTL_TramoAction")
@NbBundle.Messages({
    "CTL_TramoAction=Tramo",
    "CTL_TramoTopComponent=Tramo Window",
    "HINT_TramoTopComponent=This is a Tramo window"
})
public final class TramoTopComponent extends WorkspaceTsTopComponent<TramoDocument> {

    @ClassNameConstant
    public static final String ID = "jdplus.tramoseats.desktop.plugin.tramo.ui.TramoTopComponent";

    private final ExplorerManager mgr = new ExplorerManager();

    private static TramoDocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(TramoDocumentManager.class);
    }

    public TramoTopComponent() {
        this(null);
    }

    public TramoTopComponent(WorkspaceItem<TramoDocument> doc) {
        super(doc);
        initComponents();
        setToolTipText(NbBundle.getMessage(TramoTopComponent.class, "HINT_TramoTopComponent"));
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
    }

    private void updateUserInterfaceContext() {
        if (getDocument() == null) {
            return;
        }
        TramoDocument element = getElement();
        if (element == null) {
            UserInterfaceContext.INSTANCE.setDomain(null);
        } else {
            TramoSpec s = element.getSpecification();
            if (s == null) {
                UserInterfaceContext.INSTANCE.setAnnualFrequency(0);
            } else {
                UserInterfaceContext.INSTANCE.setAnnualFrequency(s.getFrequency());
            }
        }
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    @Override
    protected TsProcessingViewer initViewer() {
        return TsProcessingViewer.create(getElement(), DocumentUIServices.forDocument(TramoDocument.class));
    }

    @Override
    public WorkspaceItem<TramoDocument> newDocument() {
        return manager().create(WorkspaceFactory.getInstance().getActiveWorkspace());
    }

    @Override
    public void componentActivated() {
        super.componentActivated();
        updateUserInterfaceContext();
    }

    @Override
    public void componentDeactivated() {
        super.componentDeactivated();
        UserInterfaceContext.INSTANCE.setAnnualFrequency(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return TramoDocumentManager.CONTEXTPATH;
    }

    @Override
    public boolean update(TramoDocument element, Ts s) {
        if (s != null) {
            TsDomain domain = s.getData().getDomain();
            UserInterfaceContext.INSTANCE.setDomain(domain);
            TramoSpec nspec = element.getSpecification().setFrequency(domain.getAnnualFrequency());
            element.set(nspec, s);
        } else {
            UserInterfaceContext.INSTANCE.setDomain(null);
            element.set(s);
        }
        return true;
    }

}
