// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: x13.proto
// Protobuf Java Version: 4.30.2

package jdplus.x13.base.protobuf;

public interface DiagnosticsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:x13.Diagnostics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.x13.MStatistics mstatistics = 1;</code>
   * @return Whether the mstatistics field is set.
   */
  boolean hasMstatistics();
  /**
   * <code>.x13.MStatistics mstatistics = 1;</code>
   * @return The mstatistics.
   */
  jdplus.x13.base.protobuf.MStatistics getMstatistics();
  /**
   * <code>.x13.MStatistics mstatistics = 1;</code>
   */
  jdplus.x13.base.protobuf.MStatisticsOrBuilder getMstatisticsOrBuilder();
}
