// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: x13.proto
// Protobuf Java Version: 4.30.2

package jdplus.x13.base.protobuf;

/**
 * Protobuf type {@code x13.Spec}
 */
public final class Spec extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:x13.Spec)
    SpecOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      Spec.class.getName());
  }
  // Use Spec.newBuilder() to construct.
  private Spec(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Spec() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_Spec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_Spec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jdplus.x13.base.protobuf.Spec.class, jdplus.x13.base.protobuf.Spec.Builder.class);
  }

  private int bitField0_;
  public static final int REGARIMA_FIELD_NUMBER = 1;
  private jdplus.x13.base.protobuf.RegArimaSpec regarima_;
  /**
   * <code>.x13.RegArimaSpec regarima = 1;</code>
   * @return Whether the regarima field is set.
   */
  @java.lang.Override
  public boolean hasRegarima() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.x13.RegArimaSpec regarima = 1;</code>
   * @return The regarima.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.RegArimaSpec getRegarima() {
    return regarima_ == null ? jdplus.x13.base.protobuf.RegArimaSpec.getDefaultInstance() : regarima_;
  }
  /**
   * <code>.x13.RegArimaSpec regarima = 1;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.RegArimaSpecOrBuilder getRegarimaOrBuilder() {
    return regarima_ == null ? jdplus.x13.base.protobuf.RegArimaSpec.getDefaultInstance() : regarima_;
  }

  public static final int X11_FIELD_NUMBER = 2;
  private jdplus.x13.base.protobuf.X11Spec x11_;
  /**
   * <code>.x13.X11Spec x11 = 2;</code>
   * @return Whether the x11 field is set.
   */
  @java.lang.Override
  public boolean hasX11() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.x13.X11Spec x11 = 2;</code>
   * @return The x11.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X11Spec getX11() {
    return x11_ == null ? jdplus.x13.base.protobuf.X11Spec.getDefaultInstance() : x11_;
  }
  /**
   * <code>.x13.X11Spec x11 = 2;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X11SpecOrBuilder getX11OrBuilder() {
    return x11_ == null ? jdplus.x13.base.protobuf.X11Spec.getDefaultInstance() : x11_;
  }

  public static final int BENCHMARKING_FIELD_NUMBER = 3;
  private jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec benchmarking_;
  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   * @return Whether the benchmarking field is set.
   */
  @java.lang.Override
  public boolean hasBenchmarking() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   * @return The benchmarking.
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec getBenchmarking() {
    return benchmarking_ == null ? jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.getDefaultInstance() : benchmarking_;
  }
  /**
   * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpecOrBuilder getBenchmarkingOrBuilder() {
    return benchmarking_ == null ? jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.getDefaultInstance() : benchmarking_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getRegarima());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getX11());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getBenchmarking());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRegarima());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getX11());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBenchmarking());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jdplus.x13.base.protobuf.Spec)) {
      return super.equals(obj);
    }
    jdplus.x13.base.protobuf.Spec other = (jdplus.x13.base.protobuf.Spec) obj;

    if (hasRegarima() != other.hasRegarima()) return false;
    if (hasRegarima()) {
      if (!getRegarima()
          .equals(other.getRegarima())) return false;
    }
    if (hasX11() != other.hasX11()) return false;
    if (hasX11()) {
      if (!getX11()
          .equals(other.getX11())) return false;
    }
    if (hasBenchmarking() != other.hasBenchmarking()) return false;
    if (hasBenchmarking()) {
      if (!getBenchmarking()
          .equals(other.getBenchmarking())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRegarima()) {
      hash = (37 * hash) + REGARIMA_FIELD_NUMBER;
      hash = (53 * hash) + getRegarima().hashCode();
    }
    if (hasX11()) {
      hash = (37 * hash) + X11_FIELD_NUMBER;
      hash = (53 * hash) + getX11().hashCode();
    }
    if (hasBenchmarking()) {
      hash = (37 * hash) + BENCHMARKING_FIELD_NUMBER;
      hash = (53 * hash) + getBenchmarking().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jdplus.x13.base.protobuf.Spec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jdplus.x13.base.protobuf.Spec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jdplus.x13.base.protobuf.Spec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.Spec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jdplus.x13.base.protobuf.Spec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code x13.Spec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:x13.Spec)
      jdplus.x13.base.protobuf.SpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_Spec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_Spec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jdplus.x13.base.protobuf.Spec.class, jdplus.x13.base.protobuf.Spec.Builder.class);
    }

    // Construct using jdplus.x13.base.protobuf.Spec.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRegarimaFieldBuilder();
        internalGetX11FieldBuilder();
        internalGetBenchmarkingFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      regarima_ = null;
      if (regarimaBuilder_ != null) {
        regarimaBuilder_.dispose();
        regarimaBuilder_ = null;
      }
      x11_ = null;
      if (x11Builder_ != null) {
        x11Builder_.dispose();
        x11Builder_ = null;
      }
      benchmarking_ = null;
      if (benchmarkingBuilder_ != null) {
        benchmarkingBuilder_.dispose();
        benchmarkingBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_Spec_descriptor;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.Spec getDefaultInstanceForType() {
      return jdplus.x13.base.protobuf.Spec.getDefaultInstance();
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.Spec build() {
      jdplus.x13.base.protobuf.Spec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.Spec buildPartial() {
      jdplus.x13.base.protobuf.Spec result = new jdplus.x13.base.protobuf.Spec(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jdplus.x13.base.protobuf.Spec result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.regarima_ = regarimaBuilder_ == null
            ? regarima_
            : regarimaBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.x11_ = x11Builder_ == null
            ? x11_
            : x11Builder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.benchmarking_ = benchmarkingBuilder_ == null
            ? benchmarking_
            : benchmarkingBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jdplus.x13.base.protobuf.Spec) {
        return mergeFrom((jdplus.x13.base.protobuf.Spec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jdplus.x13.base.protobuf.Spec other) {
      if (other == jdplus.x13.base.protobuf.Spec.getDefaultInstance()) return this;
      if (other.hasRegarima()) {
        mergeRegarima(other.getRegarima());
      }
      if (other.hasX11()) {
        mergeX11(other.getX11());
      }
      if (other.hasBenchmarking()) {
        mergeBenchmarking(other.getBenchmarking());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetRegarimaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetX11FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetBenchmarkingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private jdplus.x13.base.protobuf.RegArimaSpec regarima_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.RegArimaSpec, jdplus.x13.base.protobuf.RegArimaSpec.Builder, jdplus.x13.base.protobuf.RegArimaSpecOrBuilder> regarimaBuilder_;
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     * @return Whether the regarima field is set.
     */
    public boolean hasRegarima() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     * @return The regarima.
     */
    public jdplus.x13.base.protobuf.RegArimaSpec getRegarima() {
      if (regarimaBuilder_ == null) {
        return regarima_ == null ? jdplus.x13.base.protobuf.RegArimaSpec.getDefaultInstance() : regarima_;
      } else {
        return regarimaBuilder_.getMessage();
      }
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public Builder setRegarima(jdplus.x13.base.protobuf.RegArimaSpec value) {
      if (regarimaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        regarima_ = value;
      } else {
        regarimaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public Builder setRegarima(
        jdplus.x13.base.protobuf.RegArimaSpec.Builder builderForValue) {
      if (regarimaBuilder_ == null) {
        regarima_ = builderForValue.build();
      } else {
        regarimaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public Builder mergeRegarima(jdplus.x13.base.protobuf.RegArimaSpec value) {
      if (regarimaBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          regarima_ != null &&
          regarima_ != jdplus.x13.base.protobuf.RegArimaSpec.getDefaultInstance()) {
          getRegarimaBuilder().mergeFrom(value);
        } else {
          regarima_ = value;
        }
      } else {
        regarimaBuilder_.mergeFrom(value);
      }
      if (regarima_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public Builder clearRegarima() {
      bitField0_ = (bitField0_ & ~0x00000001);
      regarima_ = null;
      if (regarimaBuilder_ != null) {
        regarimaBuilder_.dispose();
        regarimaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public jdplus.x13.base.protobuf.RegArimaSpec.Builder getRegarimaBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetRegarimaFieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    public jdplus.x13.base.protobuf.RegArimaSpecOrBuilder getRegarimaOrBuilder() {
      if (regarimaBuilder_ != null) {
        return regarimaBuilder_.getMessageOrBuilder();
      } else {
        return regarima_ == null ?
            jdplus.x13.base.protobuf.RegArimaSpec.getDefaultInstance() : regarima_;
      }
    }
    /**
     * <code>.x13.RegArimaSpec regarima = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.RegArimaSpec, jdplus.x13.base.protobuf.RegArimaSpec.Builder, jdplus.x13.base.protobuf.RegArimaSpecOrBuilder> 
        internalGetRegarimaFieldBuilder() {
      if (regarimaBuilder_ == null) {
        regarimaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.RegArimaSpec, jdplus.x13.base.protobuf.RegArimaSpec.Builder, jdplus.x13.base.protobuf.RegArimaSpecOrBuilder>(
                getRegarima(),
                getParentForChildren(),
                isClean());
        regarima_ = null;
      }
      return regarimaBuilder_;
    }

    private jdplus.x13.base.protobuf.X11Spec x11_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X11Spec, jdplus.x13.base.protobuf.X11Spec.Builder, jdplus.x13.base.protobuf.X11SpecOrBuilder> x11Builder_;
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     * @return Whether the x11 field is set.
     */
    public boolean hasX11() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     * @return The x11.
     */
    public jdplus.x13.base.protobuf.X11Spec getX11() {
      if (x11Builder_ == null) {
        return x11_ == null ? jdplus.x13.base.protobuf.X11Spec.getDefaultInstance() : x11_;
      } else {
        return x11Builder_.getMessage();
      }
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public Builder setX11(jdplus.x13.base.protobuf.X11Spec value) {
      if (x11Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        x11_ = value;
      } else {
        x11Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public Builder setX11(
        jdplus.x13.base.protobuf.X11Spec.Builder builderForValue) {
      if (x11Builder_ == null) {
        x11_ = builderForValue.build();
      } else {
        x11Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public Builder mergeX11(jdplus.x13.base.protobuf.X11Spec value) {
      if (x11Builder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          x11_ != null &&
          x11_ != jdplus.x13.base.protobuf.X11Spec.getDefaultInstance()) {
          getX11Builder().mergeFrom(value);
        } else {
          x11_ = value;
        }
      } else {
        x11Builder_.mergeFrom(value);
      }
      if (x11_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public Builder clearX11() {
      bitField0_ = (bitField0_ & ~0x00000002);
      x11_ = null;
      if (x11Builder_ != null) {
        x11Builder_.dispose();
        x11Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public jdplus.x13.base.protobuf.X11Spec.Builder getX11Builder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetX11FieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    public jdplus.x13.base.protobuf.X11SpecOrBuilder getX11OrBuilder() {
      if (x11Builder_ != null) {
        return x11Builder_.getMessageOrBuilder();
      } else {
        return x11_ == null ?
            jdplus.x13.base.protobuf.X11Spec.getDefaultInstance() : x11_;
      }
    }
    /**
     * <code>.x13.X11Spec x11 = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X11Spec, jdplus.x13.base.protobuf.X11Spec.Builder, jdplus.x13.base.protobuf.X11SpecOrBuilder> 
        internalGetX11FieldBuilder() {
      if (x11Builder_ == null) {
        x11Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.X11Spec, jdplus.x13.base.protobuf.X11Spec.Builder, jdplus.x13.base.protobuf.X11SpecOrBuilder>(
                getX11(),
                getParentForChildren(),
                isClean());
        x11_ = null;
      }
      return x11Builder_;
    }

    private jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec benchmarking_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.Builder, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpecOrBuilder> benchmarkingBuilder_;
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     * @return Whether the benchmarking field is set.
     */
    public boolean hasBenchmarking() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     * @return The benchmarking.
     */
    public jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec getBenchmarking() {
      if (benchmarkingBuilder_ == null) {
        return benchmarking_ == null ? jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.getDefaultInstance() : benchmarking_;
      } else {
        return benchmarkingBuilder_.getMessage();
      }
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public Builder setBenchmarking(jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec value) {
      if (benchmarkingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        benchmarking_ = value;
      } else {
        benchmarkingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public Builder setBenchmarking(
        jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.Builder builderForValue) {
      if (benchmarkingBuilder_ == null) {
        benchmarking_ = builderForValue.build();
      } else {
        benchmarkingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public Builder mergeBenchmarking(jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec value) {
      if (benchmarkingBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          benchmarking_ != null &&
          benchmarking_ != jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.getDefaultInstance()) {
          getBenchmarkingBuilder().mergeFrom(value);
        } else {
          benchmarking_ = value;
        }
      } else {
        benchmarkingBuilder_.mergeFrom(value);
      }
      if (benchmarking_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public Builder clearBenchmarking() {
      bitField0_ = (bitField0_ & ~0x00000004);
      benchmarking_ = null;
      if (benchmarkingBuilder_ != null) {
        benchmarkingBuilder_.dispose();
        benchmarkingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.Builder getBenchmarkingBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetBenchmarkingFieldBuilder().getBuilder();
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpecOrBuilder getBenchmarkingOrBuilder() {
      if (benchmarkingBuilder_ != null) {
        return benchmarkingBuilder_.getMessageOrBuilder();
      } else {
        return benchmarking_ == null ?
            jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.getDefaultInstance() : benchmarking_;
      }
    }
    /**
     * <code>.sa.BenchmarkingSpec benchmarking = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.Builder, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpecOrBuilder> 
        internalGetBenchmarkingFieldBuilder() {
      if (benchmarkingBuilder_ == null) {
        benchmarkingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpec.Builder, jdplus.sa.base.protobuf.SaProtos.BenchmarkingSpecOrBuilder>(
                getBenchmarking(),
                getParentForChildren(),
                isClean());
        benchmarking_ = null;
      }
      return benchmarkingBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:x13.Spec)
  }

  // @@protoc_insertion_point(class_scope:x13.Spec)
  private static final jdplus.x13.base.protobuf.Spec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jdplus.x13.base.protobuf.Spec();
  }

  public static jdplus.x13.base.protobuf.Spec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Spec>
      PARSER = new com.google.protobuf.AbstractParser<Spec>() {
    @java.lang.Override
    public Spec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Spec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Spec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jdplus.x13.base.protobuf.Spec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

