// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: x13.proto
// Protobuf Java Version: 4.30.2

package jdplus.x13.base.protobuf;

/**
 * Protobuf type {@code x13.X13Finals}
 */
public final class X13Finals extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:x13.X13Finals)
    X13FinalsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      X13Finals.class.getName());
  }
  // Use X13Finals.newBuilder() to construct.
  private X13Finals(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private X13Finals() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Finals_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Finals_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jdplus.x13.base.protobuf.X13Finals.class, jdplus.x13.base.protobuf.X13Finals.Builder.class);
  }

  private int bitField0_;
  public static final int D11FINAL_FIELD_NUMBER = 1;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d11Final_;
  /**
   * <code>.jd3.TsData d11final = 1;</code>
   * @return Whether the d11final field is set.
   */
  @java.lang.Override
  public boolean hasD11Final() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.jd3.TsData d11final = 1;</code>
   * @return The d11final.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD11Final() {
    return d11Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11Final_;
  }
  /**
   * <code>.jd3.TsData d11final = 1;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD11FinalOrBuilder() {
    return d11Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11Final_;
  }

  public static final int D12FINAL_FIELD_NUMBER = 2;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d12Final_;
  /**
   * <code>.jd3.TsData d12final = 2;</code>
   * @return Whether the d12final field is set.
   */
  @java.lang.Override
  public boolean hasD12Final() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.jd3.TsData d12final = 2;</code>
   * @return The d12final.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD12Final() {
    return d12Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12Final_;
  }
  /**
   * <code>.jd3.TsData d12final = 2;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD12FinalOrBuilder() {
    return d12Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12Final_;
  }

  public static final int D13FINAL_FIELD_NUMBER = 3;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d13Final_;
  /**
   * <code>.jd3.TsData d13final = 3;</code>
   * @return Whether the d13final field is set.
   */
  @java.lang.Override
  public boolean hasD13Final() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.jd3.TsData d13final = 3;</code>
   * @return The d13final.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD13Final() {
    return d13Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d13Final_;
  }
  /**
   * <code>.jd3.TsData d13final = 3;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD13FinalOrBuilder() {
    return d13Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d13Final_;
  }

  public static final int D16_FIELD_NUMBER = 4;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d16_;
  /**
   * <code>.jd3.TsData d16 = 4;</code>
   * @return Whether the d16 field is set.
   */
  @java.lang.Override
  public boolean hasD16() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.jd3.TsData d16 = 4;</code>
   * @return The d16.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD16() {
    return d16_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16_;
  }
  /**
   * <code>.jd3.TsData d16 = 4;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD16OrBuilder() {
    return d16_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16_;
  }

  public static final int D18_FIELD_NUMBER = 5;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d18_;
  /**
   * <code>.jd3.TsData d18 = 5;</code>
   * @return Whether the d18 field is set.
   */
  @java.lang.Override
  public boolean hasD18() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.jd3.TsData d18 = 5;</code>
   * @return The d18.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD18() {
    return d18_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18_;
  }
  /**
   * <code>.jd3.TsData d18 = 5;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD18OrBuilder() {
    return d18_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18_;
  }

  public static final int D11A_FIELD_NUMBER = 6;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d11A_;
  /**
   * <code>.jd3.TsData d11a = 6;</code>
   * @return Whether the d11a field is set.
   */
  @java.lang.Override
  public boolean hasD11A() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.jd3.TsData d11a = 6;</code>
   * @return The d11a.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD11A() {
    return d11A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11A_;
  }
  /**
   * <code>.jd3.TsData d11a = 6;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD11AOrBuilder() {
    return d11A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11A_;
  }

  public static final int D12A_FIELD_NUMBER = 7;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d12A_;
  /**
   * <code>.jd3.TsData d12a = 7;</code>
   * @return Whether the d12a field is set.
   */
  @java.lang.Override
  public boolean hasD12A() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.jd3.TsData d12a = 7;</code>
   * @return The d12a.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD12A() {
    return d12A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12A_;
  }
  /**
   * <code>.jd3.TsData d12a = 7;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD12AOrBuilder() {
    return d12A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12A_;
  }

  public static final int D16A_FIELD_NUMBER = 8;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d16A_;
  /**
   * <code>.jd3.TsData d16a = 8;</code>
   * @return Whether the d16a field is set.
   */
  @java.lang.Override
  public boolean hasD16A() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.jd3.TsData d16a = 8;</code>
   * @return The d16a.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD16A() {
    return d16A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16A_;
  }
  /**
   * <code>.jd3.TsData d16a = 8;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD16AOrBuilder() {
    return d16A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16A_;
  }

  public static final int D18A_FIELD_NUMBER = 9;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d18A_;
  /**
   * <code>.jd3.TsData d18a = 9;</code>
   * @return Whether the d18a field is set.
   */
  @java.lang.Override
  public boolean hasD18A() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>.jd3.TsData d18a = 9;</code>
   * @return The d18a.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD18A() {
    return d18A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18A_;
  }
  /**
   * <code>.jd3.TsData d18a = 9;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD18AOrBuilder() {
    return d18A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18A_;
  }

  public static final int E1_FIELD_NUMBER = 10;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e1_;
  /**
   * <code>.jd3.TsData e1 = 10;</code>
   * @return Whether the e1 field is set.
   */
  @java.lang.Override
  public boolean hasE1() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>.jd3.TsData e1 = 10;</code>
   * @return The e1.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE1() {
    return e1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e1_;
  }
  /**
   * <code>.jd3.TsData e1 = 10;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE1OrBuilder() {
    return e1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e1_;
  }

  public static final int E2_FIELD_NUMBER = 11;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e2_;
  /**
   * <code>.jd3.TsData e2 = 11;</code>
   * @return Whether the e2 field is set.
   */
  @java.lang.Override
  public boolean hasE2() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>.jd3.TsData e2 = 11;</code>
   * @return The e2.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE2() {
    return e2_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e2_;
  }
  /**
   * <code>.jd3.TsData e2 = 11;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE2OrBuilder() {
    return e2_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e2_;
  }

  public static final int E3_FIELD_NUMBER = 12;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e3_;
  /**
   * <code>.jd3.TsData e3 = 12;</code>
   * @return Whether the e3 field is set.
   */
  @java.lang.Override
  public boolean hasE3() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>.jd3.TsData e3 = 12;</code>
   * @return The e3.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE3() {
    return e3_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e3_;
  }
  /**
   * <code>.jd3.TsData e3 = 12;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE3OrBuilder() {
    return e3_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e3_;
  }

  public static final int E11_FIELD_NUMBER = 13;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e11_;
  /**
   * <code>.jd3.TsData e11 = 13;</code>
   * @return Whether the e11 field is set.
   */
  @java.lang.Override
  public boolean hasE11() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>.jd3.TsData e11 = 13;</code>
   * @return The e11.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE11() {
    return e11_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e11_;
  }
  /**
   * <code>.jd3.TsData e11 = 13;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE11OrBuilder() {
    return e11_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e11_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getD11Final());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getD12Final());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getD13Final());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getD16());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getD18());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getD11A());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getD12A());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeMessage(8, getD16A());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      output.writeMessage(9, getD18A());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      output.writeMessage(10, getE1());
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      output.writeMessage(11, getE2());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      output.writeMessage(12, getE3());
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      output.writeMessage(13, getE11());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getD11Final());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getD12Final());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getD13Final());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getD16());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getD18());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getD11A());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getD12A());
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getD16A());
    }
    if (((bitField0_ & 0x00000100) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getD18A());
    }
    if (((bitField0_ & 0x00000200) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, getE1());
    }
    if (((bitField0_ & 0x00000400) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getE2());
    }
    if (((bitField0_ & 0x00000800) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(12, getE3());
    }
    if (((bitField0_ & 0x00001000) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getE11());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jdplus.x13.base.protobuf.X13Finals)) {
      return super.equals(obj);
    }
    jdplus.x13.base.protobuf.X13Finals other = (jdplus.x13.base.protobuf.X13Finals) obj;

    if (hasD11Final() != other.hasD11Final()) return false;
    if (hasD11Final()) {
      if (!getD11Final()
          .equals(other.getD11Final())) return false;
    }
    if (hasD12Final() != other.hasD12Final()) return false;
    if (hasD12Final()) {
      if (!getD12Final()
          .equals(other.getD12Final())) return false;
    }
    if (hasD13Final() != other.hasD13Final()) return false;
    if (hasD13Final()) {
      if (!getD13Final()
          .equals(other.getD13Final())) return false;
    }
    if (hasD16() != other.hasD16()) return false;
    if (hasD16()) {
      if (!getD16()
          .equals(other.getD16())) return false;
    }
    if (hasD18() != other.hasD18()) return false;
    if (hasD18()) {
      if (!getD18()
          .equals(other.getD18())) return false;
    }
    if (hasD11A() != other.hasD11A()) return false;
    if (hasD11A()) {
      if (!getD11A()
          .equals(other.getD11A())) return false;
    }
    if (hasD12A() != other.hasD12A()) return false;
    if (hasD12A()) {
      if (!getD12A()
          .equals(other.getD12A())) return false;
    }
    if (hasD16A() != other.hasD16A()) return false;
    if (hasD16A()) {
      if (!getD16A()
          .equals(other.getD16A())) return false;
    }
    if (hasD18A() != other.hasD18A()) return false;
    if (hasD18A()) {
      if (!getD18A()
          .equals(other.getD18A())) return false;
    }
    if (hasE1() != other.hasE1()) return false;
    if (hasE1()) {
      if (!getE1()
          .equals(other.getE1())) return false;
    }
    if (hasE2() != other.hasE2()) return false;
    if (hasE2()) {
      if (!getE2()
          .equals(other.getE2())) return false;
    }
    if (hasE3() != other.hasE3()) return false;
    if (hasE3()) {
      if (!getE3()
          .equals(other.getE3())) return false;
    }
    if (hasE11() != other.hasE11()) return false;
    if (hasE11()) {
      if (!getE11()
          .equals(other.getE11())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasD11Final()) {
      hash = (37 * hash) + D11FINAL_FIELD_NUMBER;
      hash = (53 * hash) + getD11Final().hashCode();
    }
    if (hasD12Final()) {
      hash = (37 * hash) + D12FINAL_FIELD_NUMBER;
      hash = (53 * hash) + getD12Final().hashCode();
    }
    if (hasD13Final()) {
      hash = (37 * hash) + D13FINAL_FIELD_NUMBER;
      hash = (53 * hash) + getD13Final().hashCode();
    }
    if (hasD16()) {
      hash = (37 * hash) + D16_FIELD_NUMBER;
      hash = (53 * hash) + getD16().hashCode();
    }
    if (hasD18()) {
      hash = (37 * hash) + D18_FIELD_NUMBER;
      hash = (53 * hash) + getD18().hashCode();
    }
    if (hasD11A()) {
      hash = (37 * hash) + D11A_FIELD_NUMBER;
      hash = (53 * hash) + getD11A().hashCode();
    }
    if (hasD12A()) {
      hash = (37 * hash) + D12A_FIELD_NUMBER;
      hash = (53 * hash) + getD12A().hashCode();
    }
    if (hasD16A()) {
      hash = (37 * hash) + D16A_FIELD_NUMBER;
      hash = (53 * hash) + getD16A().hashCode();
    }
    if (hasD18A()) {
      hash = (37 * hash) + D18A_FIELD_NUMBER;
      hash = (53 * hash) + getD18A().hashCode();
    }
    if (hasE1()) {
      hash = (37 * hash) + E1_FIELD_NUMBER;
      hash = (53 * hash) + getE1().hashCode();
    }
    if (hasE2()) {
      hash = (37 * hash) + E2_FIELD_NUMBER;
      hash = (53 * hash) + getE2().hashCode();
    }
    if (hasE3()) {
      hash = (37 * hash) + E3_FIELD_NUMBER;
      hash = (53 * hash) + getE3().hashCode();
    }
    if (hasE11()) {
      hash = (37 * hash) + E11_FIELD_NUMBER;
      hash = (53 * hash) + getE11().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jdplus.x13.base.protobuf.X13Finals parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jdplus.x13.base.protobuf.X13Finals parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Finals parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jdplus.x13.base.protobuf.X13Finals prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code x13.X13Finals}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:x13.X13Finals)
      jdplus.x13.base.protobuf.X13FinalsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Finals_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Finals_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jdplus.x13.base.protobuf.X13Finals.class, jdplus.x13.base.protobuf.X13Finals.Builder.class);
    }

    // Construct using jdplus.x13.base.protobuf.X13Finals.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetD11FinalFieldBuilder();
        internalGetD12FinalFieldBuilder();
        internalGetD13FinalFieldBuilder();
        internalGetD16FieldBuilder();
        internalGetD18FieldBuilder();
        internalGetD11AFieldBuilder();
        internalGetD12AFieldBuilder();
        internalGetD16AFieldBuilder();
        internalGetD18AFieldBuilder();
        internalGetE1FieldBuilder();
        internalGetE2FieldBuilder();
        internalGetE3FieldBuilder();
        internalGetE11FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      d11Final_ = null;
      if (d11FinalBuilder_ != null) {
        d11FinalBuilder_.dispose();
        d11FinalBuilder_ = null;
      }
      d12Final_ = null;
      if (d12FinalBuilder_ != null) {
        d12FinalBuilder_.dispose();
        d12FinalBuilder_ = null;
      }
      d13Final_ = null;
      if (d13FinalBuilder_ != null) {
        d13FinalBuilder_.dispose();
        d13FinalBuilder_ = null;
      }
      d16_ = null;
      if (d16Builder_ != null) {
        d16Builder_.dispose();
        d16Builder_ = null;
      }
      d18_ = null;
      if (d18Builder_ != null) {
        d18Builder_.dispose();
        d18Builder_ = null;
      }
      d11A_ = null;
      if (d11ABuilder_ != null) {
        d11ABuilder_.dispose();
        d11ABuilder_ = null;
      }
      d12A_ = null;
      if (d12ABuilder_ != null) {
        d12ABuilder_.dispose();
        d12ABuilder_ = null;
      }
      d16A_ = null;
      if (d16ABuilder_ != null) {
        d16ABuilder_.dispose();
        d16ABuilder_ = null;
      }
      d18A_ = null;
      if (d18ABuilder_ != null) {
        d18ABuilder_.dispose();
        d18ABuilder_ = null;
      }
      e1_ = null;
      if (e1Builder_ != null) {
        e1Builder_.dispose();
        e1Builder_ = null;
      }
      e2_ = null;
      if (e2Builder_ != null) {
        e2Builder_.dispose();
        e2Builder_ = null;
      }
      e3_ = null;
      if (e3Builder_ != null) {
        e3Builder_.dispose();
        e3Builder_ = null;
      }
      e11_ = null;
      if (e11Builder_ != null) {
        e11Builder_.dispose();
        e11Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Finals_descriptor;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Finals getDefaultInstanceForType() {
      return jdplus.x13.base.protobuf.X13Finals.getDefaultInstance();
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Finals build() {
      jdplus.x13.base.protobuf.X13Finals result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Finals buildPartial() {
      jdplus.x13.base.protobuf.X13Finals result = new jdplus.x13.base.protobuf.X13Finals(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jdplus.x13.base.protobuf.X13Finals result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.d11Final_ = d11FinalBuilder_ == null
            ? d11Final_
            : d11FinalBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.d12Final_ = d12FinalBuilder_ == null
            ? d12Final_
            : d12FinalBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.d13Final_ = d13FinalBuilder_ == null
            ? d13Final_
            : d13FinalBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.d16_ = d16Builder_ == null
            ? d16_
            : d16Builder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.d18_ = d18Builder_ == null
            ? d18_
            : d18Builder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.d11A_ = d11ABuilder_ == null
            ? d11A_
            : d11ABuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.d12A_ = d12ABuilder_ == null
            ? d12A_
            : d12ABuilder_.build();
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.d16A_ = d16ABuilder_ == null
            ? d16A_
            : d16ABuilder_.build();
        to_bitField0_ |= 0x00000080;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.d18A_ = d18ABuilder_ == null
            ? d18A_
            : d18ABuilder_.build();
        to_bitField0_ |= 0x00000100;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.e1_ = e1Builder_ == null
            ? e1_
            : e1Builder_.build();
        to_bitField0_ |= 0x00000200;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.e2_ = e2Builder_ == null
            ? e2_
            : e2Builder_.build();
        to_bitField0_ |= 0x00000400;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.e3_ = e3Builder_ == null
            ? e3_
            : e3Builder_.build();
        to_bitField0_ |= 0x00000800;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.e11_ = e11Builder_ == null
            ? e11_
            : e11Builder_.build();
        to_bitField0_ |= 0x00001000;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jdplus.x13.base.protobuf.X13Finals) {
        return mergeFrom((jdplus.x13.base.protobuf.X13Finals)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jdplus.x13.base.protobuf.X13Finals other) {
      if (other == jdplus.x13.base.protobuf.X13Finals.getDefaultInstance()) return this;
      if (other.hasD11Final()) {
        mergeD11Final(other.getD11Final());
      }
      if (other.hasD12Final()) {
        mergeD12Final(other.getD12Final());
      }
      if (other.hasD13Final()) {
        mergeD13Final(other.getD13Final());
      }
      if (other.hasD16()) {
        mergeD16(other.getD16());
      }
      if (other.hasD18()) {
        mergeD18(other.getD18());
      }
      if (other.hasD11A()) {
        mergeD11A(other.getD11A());
      }
      if (other.hasD12A()) {
        mergeD12A(other.getD12A());
      }
      if (other.hasD16A()) {
        mergeD16A(other.getD16A());
      }
      if (other.hasD18A()) {
        mergeD18A(other.getD18A());
      }
      if (other.hasE1()) {
        mergeE1(other.getE1());
      }
      if (other.hasE2()) {
        mergeE2(other.getE2());
      }
      if (other.hasE3()) {
        mergeE3(other.getE3());
      }
      if (other.hasE11()) {
        mergeE11(other.getE11());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetD11FinalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetD12FinalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetD13FinalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetD16FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetD18FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetD11AFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetD12AFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  internalGetD16AFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetD18AFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              input.readMessage(
                  internalGetE1FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  internalGetE2FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              input.readMessage(
                  internalGetE3FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  internalGetE11FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d11Final_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d11FinalBuilder_;
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     * @return Whether the d11final field is set.
     */
    public boolean hasD11Final() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     * @return The d11final.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD11Final() {
      if (d11FinalBuilder_ == null) {
        return d11Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11Final_;
      } else {
        return d11FinalBuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public Builder setD11Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d11FinalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d11Final_ = value;
      } else {
        d11FinalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public Builder setD11Final(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d11FinalBuilder_ == null) {
        d11Final_ = builderForValue.build();
      } else {
        d11FinalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public Builder mergeD11Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d11FinalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          d11Final_ != null &&
          d11Final_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD11FinalBuilder().mergeFrom(value);
        } else {
          d11Final_ = value;
        }
      } else {
        d11FinalBuilder_.mergeFrom(value);
      }
      if (d11Final_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public Builder clearD11Final() {
      bitField0_ = (bitField0_ & ~0x00000001);
      d11Final_ = null;
      if (d11FinalBuilder_ != null) {
        d11FinalBuilder_.dispose();
        d11FinalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD11FinalBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetD11FinalFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD11FinalOrBuilder() {
      if (d11FinalBuilder_ != null) {
        return d11FinalBuilder_.getMessageOrBuilder();
      } else {
        return d11Final_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11Final_;
      }
    }
    /**
     * <code>.jd3.TsData d11final = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD11FinalFieldBuilder() {
      if (d11FinalBuilder_ == null) {
        d11FinalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD11Final(),
                getParentForChildren(),
                isClean());
        d11Final_ = null;
      }
      return d11FinalBuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d12Final_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d12FinalBuilder_;
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     * @return Whether the d12final field is set.
     */
    public boolean hasD12Final() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     * @return The d12final.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD12Final() {
      if (d12FinalBuilder_ == null) {
        return d12Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12Final_;
      } else {
        return d12FinalBuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public Builder setD12Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d12FinalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d12Final_ = value;
      } else {
        d12FinalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public Builder setD12Final(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d12FinalBuilder_ == null) {
        d12Final_ = builderForValue.build();
      } else {
        d12FinalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public Builder mergeD12Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d12FinalBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          d12Final_ != null &&
          d12Final_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD12FinalBuilder().mergeFrom(value);
        } else {
          d12Final_ = value;
        }
      } else {
        d12FinalBuilder_.mergeFrom(value);
      }
      if (d12Final_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public Builder clearD12Final() {
      bitField0_ = (bitField0_ & ~0x00000002);
      d12Final_ = null;
      if (d12FinalBuilder_ != null) {
        d12FinalBuilder_.dispose();
        d12FinalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD12FinalBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetD12FinalFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD12FinalOrBuilder() {
      if (d12FinalBuilder_ != null) {
        return d12FinalBuilder_.getMessageOrBuilder();
      } else {
        return d12Final_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12Final_;
      }
    }
    /**
     * <code>.jd3.TsData d12final = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD12FinalFieldBuilder() {
      if (d12FinalBuilder_ == null) {
        d12FinalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD12Final(),
                getParentForChildren(),
                isClean());
        d12Final_ = null;
      }
      return d12FinalBuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d13Final_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d13FinalBuilder_;
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     * @return Whether the d13final field is set.
     */
    public boolean hasD13Final() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     * @return The d13final.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD13Final() {
      if (d13FinalBuilder_ == null) {
        return d13Final_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d13Final_;
      } else {
        return d13FinalBuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public Builder setD13Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d13FinalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d13Final_ = value;
      } else {
        d13FinalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public Builder setD13Final(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d13FinalBuilder_ == null) {
        d13Final_ = builderForValue.build();
      } else {
        d13FinalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public Builder mergeD13Final(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d13FinalBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          d13Final_ != null &&
          d13Final_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD13FinalBuilder().mergeFrom(value);
        } else {
          d13Final_ = value;
        }
      } else {
        d13FinalBuilder_.mergeFrom(value);
      }
      if (d13Final_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public Builder clearD13Final() {
      bitField0_ = (bitField0_ & ~0x00000004);
      d13Final_ = null;
      if (d13FinalBuilder_ != null) {
        d13FinalBuilder_.dispose();
        d13FinalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD13FinalBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetD13FinalFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD13FinalOrBuilder() {
      if (d13FinalBuilder_ != null) {
        return d13FinalBuilder_.getMessageOrBuilder();
      } else {
        return d13Final_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d13Final_;
      }
    }
    /**
     * <code>.jd3.TsData d13final = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD13FinalFieldBuilder() {
      if (d13FinalBuilder_ == null) {
        d13FinalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD13Final(),
                getParentForChildren(),
                isClean());
        d13Final_ = null;
      }
      return d13FinalBuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d16_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d16Builder_;
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     * @return Whether the d16 field is set.
     */
    public boolean hasD16() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     * @return The d16.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD16() {
      if (d16Builder_ == null) {
        return d16_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16_;
      } else {
        return d16Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public Builder setD16(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d16Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d16_ = value;
      } else {
        d16Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public Builder setD16(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d16Builder_ == null) {
        d16_ = builderForValue.build();
      } else {
        d16Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public Builder mergeD16(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d16Builder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          d16_ != null &&
          d16_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD16Builder().mergeFrom(value);
        } else {
          d16_ = value;
        }
      } else {
        d16Builder_.mergeFrom(value);
      }
      if (d16_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public Builder clearD16() {
      bitField0_ = (bitField0_ & ~0x00000008);
      d16_ = null;
      if (d16Builder_ != null) {
        d16Builder_.dispose();
        d16Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD16Builder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetD16FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD16OrBuilder() {
      if (d16Builder_ != null) {
        return d16Builder_.getMessageOrBuilder();
      } else {
        return d16_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16_;
      }
    }
    /**
     * <code>.jd3.TsData d16 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD16FieldBuilder() {
      if (d16Builder_ == null) {
        d16Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD16(),
                getParentForChildren(),
                isClean());
        d16_ = null;
      }
      return d16Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d18_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d18Builder_;
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     * @return Whether the d18 field is set.
     */
    public boolean hasD18() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     * @return The d18.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD18() {
      if (d18Builder_ == null) {
        return d18_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18_;
      } else {
        return d18Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public Builder setD18(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d18Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d18_ = value;
      } else {
        d18Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public Builder setD18(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d18Builder_ == null) {
        d18_ = builderForValue.build();
      } else {
        d18Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public Builder mergeD18(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d18Builder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          d18_ != null &&
          d18_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD18Builder().mergeFrom(value);
        } else {
          d18_ = value;
        }
      } else {
        d18Builder_.mergeFrom(value);
      }
      if (d18_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public Builder clearD18() {
      bitField0_ = (bitField0_ & ~0x00000010);
      d18_ = null;
      if (d18Builder_ != null) {
        d18Builder_.dispose();
        d18Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD18Builder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetD18FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD18OrBuilder() {
      if (d18Builder_ != null) {
        return d18Builder_.getMessageOrBuilder();
      } else {
        return d18_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18_;
      }
    }
    /**
     * <code>.jd3.TsData d18 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD18FieldBuilder() {
      if (d18Builder_ == null) {
        d18Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD18(),
                getParentForChildren(),
                isClean());
        d18_ = null;
      }
      return d18Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d11A_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d11ABuilder_;
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     * @return Whether the d11a field is set.
     */
    public boolean hasD11A() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     * @return The d11a.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD11A() {
      if (d11ABuilder_ == null) {
        return d11A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11A_;
      } else {
        return d11ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public Builder setD11A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d11ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d11A_ = value;
      } else {
        d11ABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public Builder setD11A(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d11ABuilder_ == null) {
        d11A_ = builderForValue.build();
      } else {
        d11ABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public Builder mergeD11A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d11ABuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          d11A_ != null &&
          d11A_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD11ABuilder().mergeFrom(value);
        } else {
          d11A_ = value;
        }
      } else {
        d11ABuilder_.mergeFrom(value);
      }
      if (d11A_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public Builder clearD11A() {
      bitField0_ = (bitField0_ & ~0x00000020);
      d11A_ = null;
      if (d11ABuilder_ != null) {
        d11ABuilder_.dispose();
        d11ABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD11ABuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetD11AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD11AOrBuilder() {
      if (d11ABuilder_ != null) {
        return d11ABuilder_.getMessageOrBuilder();
      } else {
        return d11A_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d11A_;
      }
    }
    /**
     * <code>.jd3.TsData d11a = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD11AFieldBuilder() {
      if (d11ABuilder_ == null) {
        d11ABuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD11A(),
                getParentForChildren(),
                isClean());
        d11A_ = null;
      }
      return d11ABuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d12A_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d12ABuilder_;
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     * @return Whether the d12a field is set.
     */
    public boolean hasD12A() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     * @return The d12a.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD12A() {
      if (d12ABuilder_ == null) {
        return d12A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12A_;
      } else {
        return d12ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public Builder setD12A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d12ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d12A_ = value;
      } else {
        d12ABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public Builder setD12A(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d12ABuilder_ == null) {
        d12A_ = builderForValue.build();
      } else {
        d12ABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public Builder mergeD12A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d12ABuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          d12A_ != null &&
          d12A_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD12ABuilder().mergeFrom(value);
        } else {
          d12A_ = value;
        }
      } else {
        d12ABuilder_.mergeFrom(value);
      }
      if (d12A_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public Builder clearD12A() {
      bitField0_ = (bitField0_ & ~0x00000040);
      d12A_ = null;
      if (d12ABuilder_ != null) {
        d12ABuilder_.dispose();
        d12ABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD12ABuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetD12AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD12AOrBuilder() {
      if (d12ABuilder_ != null) {
        return d12ABuilder_.getMessageOrBuilder();
      } else {
        return d12A_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d12A_;
      }
    }
    /**
     * <code>.jd3.TsData d12a = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD12AFieldBuilder() {
      if (d12ABuilder_ == null) {
        d12ABuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD12A(),
                getParentForChildren(),
                isClean());
        d12A_ = null;
      }
      return d12ABuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d16A_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d16ABuilder_;
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     * @return Whether the d16a field is set.
     */
    public boolean hasD16A() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     * @return The d16a.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD16A() {
      if (d16ABuilder_ == null) {
        return d16A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16A_;
      } else {
        return d16ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public Builder setD16A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d16ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d16A_ = value;
      } else {
        d16ABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public Builder setD16A(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d16ABuilder_ == null) {
        d16A_ = builderForValue.build();
      } else {
        d16ABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public Builder mergeD16A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d16ABuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          d16A_ != null &&
          d16A_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD16ABuilder().mergeFrom(value);
        } else {
          d16A_ = value;
        }
      } else {
        d16ABuilder_.mergeFrom(value);
      }
      if (d16A_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public Builder clearD16A() {
      bitField0_ = (bitField0_ & ~0x00000080);
      d16A_ = null;
      if (d16ABuilder_ != null) {
        d16ABuilder_.dispose();
        d16ABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD16ABuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetD16AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD16AOrBuilder() {
      if (d16ABuilder_ != null) {
        return d16ABuilder_.getMessageOrBuilder();
      } else {
        return d16A_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d16A_;
      }
    }
    /**
     * <code>.jd3.TsData d16a = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD16AFieldBuilder() {
      if (d16ABuilder_ == null) {
        d16ABuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD16A(),
                getParentForChildren(),
                isClean());
        d16A_ = null;
      }
      return d16ABuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData d18A_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> d18ABuilder_;
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     * @return Whether the d18a field is set.
     */
    public boolean hasD18A() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     * @return The d18a.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getD18A() {
      if (d18ABuilder_ == null) {
        return d18A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18A_;
      } else {
        return d18ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public Builder setD18A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d18ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        d18A_ = value;
      } else {
        d18ABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public Builder setD18A(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (d18ABuilder_ == null) {
        d18A_ = builderForValue.build();
      } else {
        d18ABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public Builder mergeD18A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (d18ABuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          d18A_ != null &&
          d18A_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getD18ABuilder().mergeFrom(value);
        } else {
          d18A_ = value;
        }
      } else {
        d18ABuilder_.mergeFrom(value);
      }
      if (d18A_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public Builder clearD18A() {
      bitField0_ = (bitField0_ & ~0x00000100);
      d18A_ = null;
      if (d18ABuilder_ != null) {
        d18ABuilder_.dispose();
        d18ABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getD18ABuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetD18AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getD18AOrBuilder() {
      if (d18ABuilder_ != null) {
        return d18ABuilder_.getMessageOrBuilder();
      } else {
        return d18A_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : d18A_;
      }
    }
    /**
     * <code>.jd3.TsData d18a = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetD18AFieldBuilder() {
      if (d18ABuilder_ == null) {
        d18ABuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getD18A(),
                getParentForChildren(),
                isClean());
        d18A_ = null;
      }
      return d18ABuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e1_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> e1Builder_;
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     * @return Whether the e1 field is set.
     */
    public boolean hasE1() {
      return ((bitField0_ & 0x00000200) != 0);
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     * @return The e1.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE1() {
      if (e1Builder_ == null) {
        return e1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e1_;
      } else {
        return e1Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public Builder setE1(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        e1_ = value;
      } else {
        e1Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public Builder setE1(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (e1Builder_ == null) {
        e1_ = builderForValue.build();
      } else {
        e1Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public Builder mergeE1(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e1Builder_ == null) {
        if (((bitField0_ & 0x00000200) != 0) &&
          e1_ != null &&
          e1_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getE1Builder().mergeFrom(value);
        } else {
          e1_ = value;
        }
      } else {
        e1Builder_.mergeFrom(value);
      }
      if (e1_ != null) {
        bitField0_ |= 0x00000200;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public Builder clearE1() {
      bitField0_ = (bitField0_ & ~0x00000200);
      e1_ = null;
      if (e1Builder_ != null) {
        e1Builder_.dispose();
        e1Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getE1Builder() {
      bitField0_ |= 0x00000200;
      onChanged();
      return internalGetE1FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE1OrBuilder() {
      if (e1Builder_ != null) {
        return e1Builder_.getMessageOrBuilder();
      } else {
        return e1_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e1_;
      }
    }
    /**
     * <code>.jd3.TsData e1 = 10;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetE1FieldBuilder() {
      if (e1Builder_ == null) {
        e1Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getE1(),
                getParentForChildren(),
                isClean());
        e1_ = null;
      }
      return e1Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e2_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> e2Builder_;
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     * @return Whether the e2 field is set.
     */
    public boolean hasE2() {
      return ((bitField0_ & 0x00000400) != 0);
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     * @return The e2.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE2() {
      if (e2Builder_ == null) {
        return e2_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e2_;
      } else {
        return e2Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public Builder setE2(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e2Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        e2_ = value;
      } else {
        e2Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public Builder setE2(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (e2Builder_ == null) {
        e2_ = builderForValue.build();
      } else {
        e2Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public Builder mergeE2(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e2Builder_ == null) {
        if (((bitField0_ & 0x00000400) != 0) &&
          e2_ != null &&
          e2_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getE2Builder().mergeFrom(value);
        } else {
          e2_ = value;
        }
      } else {
        e2Builder_.mergeFrom(value);
      }
      if (e2_ != null) {
        bitField0_ |= 0x00000400;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public Builder clearE2() {
      bitField0_ = (bitField0_ & ~0x00000400);
      e2_ = null;
      if (e2Builder_ != null) {
        e2Builder_.dispose();
        e2Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getE2Builder() {
      bitField0_ |= 0x00000400;
      onChanged();
      return internalGetE2FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE2OrBuilder() {
      if (e2Builder_ != null) {
        return e2Builder_.getMessageOrBuilder();
      } else {
        return e2_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e2_;
      }
    }
    /**
     * <code>.jd3.TsData e2 = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetE2FieldBuilder() {
      if (e2Builder_ == null) {
        e2Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getE2(),
                getParentForChildren(),
                isClean());
        e2_ = null;
      }
      return e2Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e3_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> e3Builder_;
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     * @return Whether the e3 field is set.
     */
    public boolean hasE3() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     * @return The e3.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE3() {
      if (e3Builder_ == null) {
        return e3_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e3_;
      } else {
        return e3Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public Builder setE3(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e3Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        e3_ = value;
      } else {
        e3Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public Builder setE3(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (e3Builder_ == null) {
        e3_ = builderForValue.build();
      } else {
        e3Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public Builder mergeE3(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e3Builder_ == null) {
        if (((bitField0_ & 0x00000800) != 0) &&
          e3_ != null &&
          e3_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getE3Builder().mergeFrom(value);
        } else {
          e3_ = value;
        }
      } else {
        e3Builder_.mergeFrom(value);
      }
      if (e3_ != null) {
        bitField0_ |= 0x00000800;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public Builder clearE3() {
      bitField0_ = (bitField0_ & ~0x00000800);
      e3_ = null;
      if (e3Builder_ != null) {
        e3Builder_.dispose();
        e3Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getE3Builder() {
      bitField0_ |= 0x00000800;
      onChanged();
      return internalGetE3FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE3OrBuilder() {
      if (e3Builder_ != null) {
        return e3Builder_.getMessageOrBuilder();
      } else {
        return e3_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e3_;
      }
    }
    /**
     * <code>.jd3.TsData e3 = 12;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetE3FieldBuilder() {
      if (e3Builder_ == null) {
        e3Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getE3(),
                getParentForChildren(),
                isClean());
        e3_ = null;
      }
      return e3Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData e11_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> e11Builder_;
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     * @return Whether the e11 field is set.
     */
    public boolean hasE11() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     * @return The e11.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getE11() {
      if (e11Builder_ == null) {
        return e11_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e11_;
      } else {
        return e11Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public Builder setE11(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e11Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        e11_ = value;
      } else {
        e11Builder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public Builder setE11(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (e11Builder_ == null) {
        e11_ = builderForValue.build();
      } else {
        e11Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public Builder mergeE11(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (e11Builder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          e11_ != null &&
          e11_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getE11Builder().mergeFrom(value);
        } else {
          e11_ = value;
        }
      } else {
        e11Builder_.mergeFrom(value);
      }
      if (e11_ != null) {
        bitField0_ |= 0x00001000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public Builder clearE11() {
      bitField0_ = (bitField0_ & ~0x00001000);
      e11_ = null;
      if (e11Builder_ != null) {
        e11Builder_.dispose();
        e11Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getE11Builder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return internalGetE11FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getE11OrBuilder() {
      if (e11Builder_ != null) {
        return e11Builder_.getMessageOrBuilder();
      } else {
        return e11_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : e11_;
      }
    }
    /**
     * <code>.jd3.TsData e11 = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetE11FieldBuilder() {
      if (e11Builder_ == null) {
        e11Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getE11(),
                getParentForChildren(),
                isClean());
        e11_ = null;
      }
      return e11Builder_;
    }

    // @@protoc_insertion_point(builder_scope:x13.X13Finals)
  }

  // @@protoc_insertion_point(class_scope:x13.X13Finals)
  private static final jdplus.x13.base.protobuf.X13Finals DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jdplus.x13.base.protobuf.X13Finals();
  }

  public static jdplus.x13.base.protobuf.X13Finals getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<X13Finals>
      PARSER = new com.google.protobuf.AbstractParser<X13Finals>() {
    @java.lang.Override
    public X13Finals parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<X13Finals> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<X13Finals> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jdplus.x13.base.protobuf.X13Finals getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

