// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: x13.proto
// Protobuf Java Version: 4.30.2

package jdplus.x13.base.protobuf;

/**
 * Protobuf type {@code x13.X13Preadjustment}
 */
public final class X13Preadjustment extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:x13.X13Preadjustment)
    X13PreadjustmentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      X13Preadjustment.class.getName());
  }
  // Use X13Preadjustment.newBuilder() to construct.
  private X13Preadjustment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private X13Preadjustment() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Preadjustment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jdplus.x13.base.protobuf.X13Preadjustment.class, jdplus.x13.base.protobuf.X13Preadjustment.Builder.class);
  }

  private int bitField0_;
  public static final int A1_FIELD_NUMBER = 1;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1_;
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return Whether the a1 field is set.
   */
  @java.lang.Override
  public boolean hasA1() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   * @return The a1.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1() {
    return a1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1_;
  }
  /**
   * <code>.jd3.TsData a1 = 1;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1OrBuilder() {
    return a1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1_;
  }

  public static final int A1A_FIELD_NUMBER = 2;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1A_;
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return Whether the a1a field is set.
   */
  @java.lang.Override
  public boolean hasA1A() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   * @return The a1a.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1A() {
    return a1A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
  }
  /**
   * <code>.jd3.TsData a1a = 2;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1AOrBuilder() {
    return a1A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
  }

  public static final int A1B_FIELD_NUMBER = 3;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1B_;
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return Whether the a1b field is set.
   */
  @java.lang.Override
  public boolean hasA1B() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   * @return The a1b.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1B() {
    return a1B_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
  }
  /**
   * <code>.jd3.TsData a1b = 3;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1BOrBuilder() {
    return a1B_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
  }

  public static final int A6_FIELD_NUMBER = 4;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a6_;
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return Whether the a6 field is set.
   */
  @java.lang.Override
  public boolean hasA6() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   * @return The a6.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA6() {
    return a6_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a6_;
  }
  /**
   * <code>.jd3.TsData a6 = 4;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA6OrBuilder() {
    return a6_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a6_;
  }

  public static final int A7_FIELD_NUMBER = 5;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a7_;
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return Whether the a7 field is set.
   */
  @java.lang.Override
  public boolean hasA7() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   * @return The a7.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA7() {
    return a7_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a7_;
  }
  /**
   * <code>.jd3.TsData a7 = 5;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA7OrBuilder() {
    return a7_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a7_;
  }

  public static final int A8_FIELD_NUMBER = 6;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a8_;
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return Whether the a8 field is set.
   */
  @java.lang.Override
  public boolean hasA8() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   * @return The a8.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA8() {
    return a8_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a8_;
  }
  /**
   * <code>.jd3.TsData a8 = 6;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA8OrBuilder() {
    return a8_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a8_;
  }

  public static final int A9_FIELD_NUMBER = 7;
  private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a9_;
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return Whether the a9 field is set.
   */
  @java.lang.Override
  public boolean hasA9() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   * @return The a9.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA9() {
    return a9_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a9_;
  }
  /**
   * <code>.jd3.TsData a9 = 7;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA9OrBuilder() {
    return a9_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a9_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getA1());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getA1A());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getA1B());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getA6());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getA7());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getA8());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeMessage(7, getA9());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getA1());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getA1A());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getA1B());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getA6());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getA7());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getA8());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getA9());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jdplus.x13.base.protobuf.X13Preadjustment)) {
      return super.equals(obj);
    }
    jdplus.x13.base.protobuf.X13Preadjustment other = (jdplus.x13.base.protobuf.X13Preadjustment) obj;

    if (hasA1() != other.hasA1()) return false;
    if (hasA1()) {
      if (!getA1()
          .equals(other.getA1())) return false;
    }
    if (hasA1A() != other.hasA1A()) return false;
    if (hasA1A()) {
      if (!getA1A()
          .equals(other.getA1A())) return false;
    }
    if (hasA1B() != other.hasA1B()) return false;
    if (hasA1B()) {
      if (!getA1B()
          .equals(other.getA1B())) return false;
    }
    if (hasA6() != other.hasA6()) return false;
    if (hasA6()) {
      if (!getA6()
          .equals(other.getA6())) return false;
    }
    if (hasA7() != other.hasA7()) return false;
    if (hasA7()) {
      if (!getA7()
          .equals(other.getA7())) return false;
    }
    if (hasA8() != other.hasA8()) return false;
    if (hasA8()) {
      if (!getA8()
          .equals(other.getA8())) return false;
    }
    if (hasA9() != other.hasA9()) return false;
    if (hasA9()) {
      if (!getA9()
          .equals(other.getA9())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasA1()) {
      hash = (37 * hash) + A1_FIELD_NUMBER;
      hash = (53 * hash) + getA1().hashCode();
    }
    if (hasA1A()) {
      hash = (37 * hash) + A1A_FIELD_NUMBER;
      hash = (53 * hash) + getA1A().hashCode();
    }
    if (hasA1B()) {
      hash = (37 * hash) + A1B_FIELD_NUMBER;
      hash = (53 * hash) + getA1B().hashCode();
    }
    if (hasA6()) {
      hash = (37 * hash) + A6_FIELD_NUMBER;
      hash = (53 * hash) + getA6().hashCode();
    }
    if (hasA7()) {
      hash = (37 * hash) + A7_FIELD_NUMBER;
      hash = (53 * hash) + getA7().hashCode();
    }
    if (hasA8()) {
      hash = (37 * hash) + A8_FIELD_NUMBER;
      hash = (53 * hash) + getA8().hashCode();
    }
    if (hasA9()) {
      hash = (37 * hash) + A9_FIELD_NUMBER;
      hash = (53 * hash) + getA9().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jdplus.x13.base.protobuf.X13Preadjustment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jdplus.x13.base.protobuf.X13Preadjustment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Preadjustment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jdplus.x13.base.protobuf.X13Preadjustment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code x13.X13Preadjustment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:x13.X13Preadjustment)
      jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Preadjustment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jdplus.x13.base.protobuf.X13Preadjustment.class, jdplus.x13.base.protobuf.X13Preadjustment.Builder.class);
    }

    // Construct using jdplus.x13.base.protobuf.X13Preadjustment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetA1FieldBuilder();
        internalGetA1AFieldBuilder();
        internalGetA1BFieldBuilder();
        internalGetA6FieldBuilder();
        internalGetA7FieldBuilder();
        internalGetA8FieldBuilder();
        internalGetA9FieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      a1_ = null;
      if (a1Builder_ != null) {
        a1Builder_.dispose();
        a1Builder_ = null;
      }
      a1A_ = null;
      if (a1ABuilder_ != null) {
        a1ABuilder_.dispose();
        a1ABuilder_ = null;
      }
      a1B_ = null;
      if (a1BBuilder_ != null) {
        a1BBuilder_.dispose();
        a1BBuilder_ = null;
      }
      a6_ = null;
      if (a6Builder_ != null) {
        a6Builder_.dispose();
        a6Builder_ = null;
      }
      a7_ = null;
      if (a7Builder_ != null) {
        a7Builder_.dispose();
        a7Builder_ = null;
      }
      a8_ = null;
      if (a8Builder_ != null) {
        a8Builder_.dispose();
        a8Builder_ = null;
      }
      a9_ = null;
      if (a9Builder_ != null) {
        a9Builder_.dispose();
        a9Builder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Preadjustment_descriptor;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Preadjustment getDefaultInstanceForType() {
      return jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance();
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Preadjustment build() {
      jdplus.x13.base.protobuf.X13Preadjustment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Preadjustment buildPartial() {
      jdplus.x13.base.protobuf.X13Preadjustment result = new jdplus.x13.base.protobuf.X13Preadjustment(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jdplus.x13.base.protobuf.X13Preadjustment result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.a1_ = a1Builder_ == null
            ? a1_
            : a1Builder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.a1A_ = a1ABuilder_ == null
            ? a1A_
            : a1ABuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.a1B_ = a1BBuilder_ == null
            ? a1B_
            : a1BBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.a6_ = a6Builder_ == null
            ? a6_
            : a6Builder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.a7_ = a7Builder_ == null
            ? a7_
            : a7Builder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.a8_ = a8Builder_ == null
            ? a8_
            : a8Builder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.a9_ = a9Builder_ == null
            ? a9_
            : a9Builder_.build();
        to_bitField0_ |= 0x00000040;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jdplus.x13.base.protobuf.X13Preadjustment) {
        return mergeFrom((jdplus.x13.base.protobuf.X13Preadjustment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jdplus.x13.base.protobuf.X13Preadjustment other) {
      if (other == jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance()) return this;
      if (other.hasA1()) {
        mergeA1(other.getA1());
      }
      if (other.hasA1A()) {
        mergeA1A(other.getA1A());
      }
      if (other.hasA1B()) {
        mergeA1B(other.getA1B());
      }
      if (other.hasA6()) {
        mergeA6(other.getA6());
      }
      if (other.hasA7()) {
        mergeA7(other.getA7());
      }
      if (other.hasA8()) {
        mergeA8(other.getA8());
      }
      if (other.hasA9()) {
        mergeA9(other.getA9());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetA1FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetA1AFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetA1BFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetA6FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetA7FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetA8FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  internalGetA9FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a1Builder_;
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     * @return Whether the a1 field is set.
     */
    public boolean hasA1() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     * @return The a1.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1() {
      if (a1Builder_ == null) {
        return a1_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1_;
      } else {
        return a1Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder setA1(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1_ = value;
      } else {
        a1Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder setA1(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1Builder_ == null) {
        a1_ = builderForValue.build();
      } else {
        a1Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder mergeA1(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1Builder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          a1_ != null &&
          a1_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA1Builder().mergeFrom(value);
        } else {
          a1_ = value;
        }
      } else {
        a1Builder_.mergeFrom(value);
      }
      if (a1_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public Builder clearA1() {
      bitField0_ = (bitField0_ & ~0x00000001);
      a1_ = null;
      if (a1Builder_ != null) {
        a1Builder_.dispose();
        a1Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA1Builder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetA1FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1OrBuilder() {
      if (a1Builder_ != null) {
        return a1Builder_.getMessageOrBuilder();
      } else {
        return a1_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1_;
      }
    }
    /**
     * <code>.jd3.TsData a1 = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA1FieldBuilder() {
      if (a1Builder_ == null) {
        a1Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA1(),
                getParentForChildren(),
                isClean());
        a1_ = null;
      }
      return a1Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1A_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a1ABuilder_;
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     * @return Whether the a1a field is set.
     */
    public boolean hasA1A() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     * @return The a1a.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1A() {
      if (a1ABuilder_ == null) {
        return a1A_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
      } else {
        return a1ABuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder setA1A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1ABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1A_ = value;
      } else {
        a1ABuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder setA1A(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1ABuilder_ == null) {
        a1A_ = builderForValue.build();
      } else {
        a1ABuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder mergeA1A(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1ABuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          a1A_ != null &&
          a1A_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA1ABuilder().mergeFrom(value);
        } else {
          a1A_ = value;
        }
      } else {
        a1ABuilder_.mergeFrom(value);
      }
      if (a1A_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public Builder clearA1A() {
      bitField0_ = (bitField0_ & ~0x00000002);
      a1A_ = null;
      if (a1ABuilder_ != null) {
        a1ABuilder_.dispose();
        a1ABuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA1ABuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetA1AFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1AOrBuilder() {
      if (a1ABuilder_ != null) {
        return a1ABuilder_.getMessageOrBuilder();
      } else {
        return a1A_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1A_;
      }
    }
    /**
     * <code>.jd3.TsData a1a = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA1AFieldBuilder() {
      if (a1ABuilder_ == null) {
        a1ABuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA1A(),
                getParentForChildren(),
                isClean());
        a1A_ = null;
      }
      return a1ABuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a1B_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a1BBuilder_;
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     * @return Whether the a1b field is set.
     */
    public boolean hasA1B() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     * @return The a1b.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA1B() {
      if (a1BBuilder_ == null) {
        return a1B_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
      } else {
        return a1BBuilder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder setA1B(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1BBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a1B_ = value;
      } else {
        a1BBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder setA1B(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a1BBuilder_ == null) {
        a1B_ = builderForValue.build();
      } else {
        a1BBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder mergeA1B(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a1BBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          a1B_ != null &&
          a1B_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA1BBuilder().mergeFrom(value);
        } else {
          a1B_ = value;
        }
      } else {
        a1BBuilder_.mergeFrom(value);
      }
      if (a1B_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public Builder clearA1B() {
      bitField0_ = (bitField0_ & ~0x00000004);
      a1B_ = null;
      if (a1BBuilder_ != null) {
        a1BBuilder_.dispose();
        a1BBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA1BBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetA1BFieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA1BOrBuilder() {
      if (a1BBuilder_ != null) {
        return a1BBuilder_.getMessageOrBuilder();
      } else {
        return a1B_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a1B_;
      }
    }
    /**
     * <code>.jd3.TsData a1b = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA1BFieldBuilder() {
      if (a1BBuilder_ == null) {
        a1BBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA1B(),
                getParentForChildren(),
                isClean());
        a1B_ = null;
      }
      return a1BBuilder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a6_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a6Builder_;
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     * @return Whether the a6 field is set.
     */
    public boolean hasA6() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     * @return The a6.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA6() {
      if (a6Builder_ == null) {
        return a6_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a6_;
      } else {
        return a6Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder setA6(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a6Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a6_ = value;
      } else {
        a6Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder setA6(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a6Builder_ == null) {
        a6_ = builderForValue.build();
      } else {
        a6Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder mergeA6(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a6Builder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          a6_ != null &&
          a6_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA6Builder().mergeFrom(value);
        } else {
          a6_ = value;
        }
      } else {
        a6Builder_.mergeFrom(value);
      }
      if (a6_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public Builder clearA6() {
      bitField0_ = (bitField0_ & ~0x00000008);
      a6_ = null;
      if (a6Builder_ != null) {
        a6Builder_.dispose();
        a6Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA6Builder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetA6FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA6OrBuilder() {
      if (a6Builder_ != null) {
        return a6Builder_.getMessageOrBuilder();
      } else {
        return a6_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a6_;
      }
    }
    /**
     * <code>.jd3.TsData a6 = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA6FieldBuilder() {
      if (a6Builder_ == null) {
        a6Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA6(),
                getParentForChildren(),
                isClean());
        a6_ = null;
      }
      return a6Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a7_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a7Builder_;
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     * @return Whether the a7 field is set.
     */
    public boolean hasA7() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     * @return The a7.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA7() {
      if (a7Builder_ == null) {
        return a7_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a7_;
      } else {
        return a7Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder setA7(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a7Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a7_ = value;
      } else {
        a7Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder setA7(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a7Builder_ == null) {
        a7_ = builderForValue.build();
      } else {
        a7Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder mergeA7(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a7Builder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          a7_ != null &&
          a7_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA7Builder().mergeFrom(value);
        } else {
          a7_ = value;
        }
      } else {
        a7Builder_.mergeFrom(value);
      }
      if (a7_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public Builder clearA7() {
      bitField0_ = (bitField0_ & ~0x00000010);
      a7_ = null;
      if (a7Builder_ != null) {
        a7Builder_.dispose();
        a7Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA7Builder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetA7FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA7OrBuilder() {
      if (a7Builder_ != null) {
        return a7Builder_.getMessageOrBuilder();
      } else {
        return a7_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a7_;
      }
    }
    /**
     * <code>.jd3.TsData a7 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA7FieldBuilder() {
      if (a7Builder_ == null) {
        a7Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA7(),
                getParentForChildren(),
                isClean());
        a7_ = null;
      }
      return a7Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a8_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a8Builder_;
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     * @return Whether the a8 field is set.
     */
    public boolean hasA8() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     * @return The a8.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA8() {
      if (a8Builder_ == null) {
        return a8_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a8_;
      } else {
        return a8Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder setA8(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a8Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a8_ = value;
      } else {
        a8Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder setA8(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a8Builder_ == null) {
        a8_ = builderForValue.build();
      } else {
        a8Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder mergeA8(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a8Builder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          a8_ != null &&
          a8_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA8Builder().mergeFrom(value);
        } else {
          a8_ = value;
        }
      } else {
        a8Builder_.mergeFrom(value);
      }
      if (a8_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public Builder clearA8() {
      bitField0_ = (bitField0_ & ~0x00000020);
      a8_ = null;
      if (a8Builder_ != null) {
        a8Builder_.dispose();
        a8Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA8Builder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetA8FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA8OrBuilder() {
      if (a8Builder_ != null) {
        return a8Builder_.getMessageOrBuilder();
      } else {
        return a8_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a8_;
      }
    }
    /**
     * <code>.jd3.TsData a8 = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA8FieldBuilder() {
      if (a8Builder_ == null) {
        a8Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA8(),
                getParentForChildren(),
                isClean());
        a8_ = null;
      }
      return a8Builder_;
    }

    private jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData a9_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> a9Builder_;
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     * @return Whether the a9 field is set.
     */
    public boolean hasA9() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     * @return The a9.
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData getA9() {
      if (a9Builder_ == null) {
        return a9_ == null ? jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a9_;
      } else {
        return a9Builder_.getMessage();
      }
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder setA9(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a9Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        a9_ = value;
      } else {
        a9Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder setA9(
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder builderForValue) {
      if (a9Builder_ == null) {
        a9_ = builderForValue.build();
      } else {
        a9Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder mergeA9(jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData value) {
      if (a9Builder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          a9_ != null &&
          a9_ != jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance()) {
          getA9Builder().mergeFrom(value);
        } else {
          a9_ = value;
        }
      } else {
        a9Builder_.mergeFrom(value);
      }
      if (a9_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public Builder clearA9() {
      bitField0_ = (bitField0_ & ~0x00000040);
      a9_ = null;
      if (a9Builder_ != null) {
        a9Builder_.dispose();
        a9Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder getA9Builder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return internalGetA9FieldBuilder().getBuilder();
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    public jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder getA9OrBuilder() {
      if (a9Builder_ != null) {
        return a9Builder_.getMessageOrBuilder();
      } else {
        return a9_ == null ?
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.getDefaultInstance() : a9_;
      }
    }
    /**
     * <code>.jd3.TsData a9 = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder> 
        internalGetA9FieldBuilder() {
      if (a9Builder_ == null) {
        a9Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsData.Builder, jdplus.toolkit.base.protobuf.toolkit.ToolkitProtos.TsDataOrBuilder>(
                getA9(),
                getParentForChildren(),
                isClean());
        a9_ = null;
      }
      return a9Builder_;
    }

    // @@protoc_insertion_point(builder_scope:x13.X13Preadjustment)
  }

  // @@protoc_insertion_point(class_scope:x13.X13Preadjustment)
  private static final jdplus.x13.base.protobuf.X13Preadjustment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jdplus.x13.base.protobuf.X13Preadjustment();
  }

  public static jdplus.x13.base.protobuf.X13Preadjustment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<X13Preadjustment>
      PARSER = new com.google.protobuf.AbstractParser<X13Preadjustment>() {
    @java.lang.Override
    public X13Preadjustment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<X13Preadjustment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<X13Preadjustment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jdplus.x13.base.protobuf.X13Preadjustment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

