// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: x13.proto
// Protobuf Java Version: 4.30.2

package jdplus.x13.base.protobuf;

/**
 * Protobuf type {@code x13.X13Results}
 */
public final class X13Results extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:x13.X13Results)
    X13ResultsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      X13Results.class.getName());
  }
  // Use X13Results.newBuilder() to construct.
  private X13Results(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private X13Results() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Results_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Results_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jdplus.x13.base.protobuf.X13Results.class, jdplus.x13.base.protobuf.X13Results.Builder.class);
  }

  private int bitField0_;
  public static final int PREADJUSTMENT_FIELD_NUMBER = 1;
  private jdplus.x13.base.protobuf.X13Preadjustment preadjustment_;
  /**
   * <code>.x13.X13Preadjustment preadjustment = 1;</code>
   * @return Whether the preadjustment field is set.
   */
  @java.lang.Override
  public boolean hasPreadjustment() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.x13.X13Preadjustment preadjustment = 1;</code>
   * @return The preadjustment.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X13Preadjustment getPreadjustment() {
    return preadjustment_ == null ? jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance() : preadjustment_;
  }
  /**
   * <code>.x13.X13Preadjustment preadjustment = 1;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder getPreadjustmentOrBuilder() {
    return preadjustment_ == null ? jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance() : preadjustment_;
  }

  public static final int PREPROCESSING_FIELD_NUMBER = 2;
  private jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel preprocessing_;
  /**
   * <code>.regarima.RegArimaModel preprocessing = 2;</code>
   * @return Whether the preprocessing field is set.
   */
  @java.lang.Override
  public boolean hasPreprocessing() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.regarima.RegArimaModel preprocessing = 2;</code>
   * @return The preprocessing.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel getPreprocessing() {
    return preprocessing_ == null ? jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
  }
  /**
   * <code>.regarima.RegArimaModel preprocessing = 2;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder getPreprocessingOrBuilder() {
    return preprocessing_ == null ? jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
  }

  public static final int DECOMPOSITION_FIELD_NUMBER = 3;
  private jdplus.x13.base.protobuf.X11Results decomposition_;
  /**
   * <code>.x13.X11Results decomposition = 3;</code>
   * @return Whether the decomposition field is set.
   */
  @java.lang.Override
  public boolean hasDecomposition() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.x13.X11Results decomposition = 3;</code>
   * @return The decomposition.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X11Results getDecomposition() {
    return decomposition_ == null ? jdplus.x13.base.protobuf.X11Results.getDefaultInstance() : decomposition_;
  }
  /**
   * <code>.x13.X11Results decomposition = 3;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X11ResultsOrBuilder getDecompositionOrBuilder() {
    return decomposition_ == null ? jdplus.x13.base.protobuf.X11Results.getDefaultInstance() : decomposition_;
  }

  public static final int FINAL_FIELD_NUMBER = 4;
  private jdplus.x13.base.protobuf.X13Finals final_;
  /**
   * <code>.x13.X13Finals final = 4;</code>
   * @return Whether the final field is set.
   */
  @java.lang.Override
  public boolean hasFinal() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.x13.X13Finals final = 4;</code>
   * @return The final.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X13Finals getFinal() {
    return final_ == null ? jdplus.x13.base.protobuf.X13Finals.getDefaultInstance() : final_;
  }
  /**
   * <code>.x13.X13Finals final = 4;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.X13FinalsOrBuilder getFinalOrBuilder() {
    return final_ == null ? jdplus.x13.base.protobuf.X13Finals.getDefaultInstance() : final_;
  }

  public static final int DIAGNOSTICS_X13_FIELD_NUMBER = 5;
  private jdplus.x13.base.protobuf.Diagnostics diagnosticsX13_;
  /**
   * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
   * @return Whether the diagnosticsX13 field is set.
   */
  @java.lang.Override
  public boolean hasDiagnosticsX13() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
   * @return The diagnosticsX13.
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.Diagnostics getDiagnosticsX13() {
    return diagnosticsX13_ == null ? jdplus.x13.base.protobuf.Diagnostics.getDefaultInstance() : diagnosticsX13_;
  }
  /**
   * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
   */
  @java.lang.Override
  public jdplus.x13.base.protobuf.DiagnosticsOrBuilder getDiagnosticsX13OrBuilder() {
    return diagnosticsX13_ == null ? jdplus.x13.base.protobuf.Diagnostics.getDefaultInstance() : diagnosticsX13_;
  }

  public static final int DIAGNOSTICS_SA_FIELD_NUMBER = 6;
  private jdplus.sa.base.protobuf.SaProtos.Diagnostics diagnosticsSa_;
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
   * @return Whether the diagnosticsSa field is set.
   */
  @java.lang.Override
  public boolean hasDiagnosticsSa() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
   * @return The diagnosticsSa.
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.Diagnostics getDiagnosticsSa() {
    return diagnosticsSa_ == null ? jdplus.sa.base.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
  }
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.DiagnosticsOrBuilder getDiagnosticsSaOrBuilder() {
    return diagnosticsSa_ == null ? jdplus.sa.base.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getPreadjustment());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getPreprocessing());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getDecomposition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeMessage(4, getFinal());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getDiagnosticsX13());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(6, getDiagnosticsSa());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPreadjustment());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPreprocessing());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDecomposition());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFinal());
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDiagnosticsX13());
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDiagnosticsSa());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jdplus.x13.base.protobuf.X13Results)) {
      return super.equals(obj);
    }
    jdplus.x13.base.protobuf.X13Results other = (jdplus.x13.base.protobuf.X13Results) obj;

    if (hasPreadjustment() != other.hasPreadjustment()) return false;
    if (hasPreadjustment()) {
      if (!getPreadjustment()
          .equals(other.getPreadjustment())) return false;
    }
    if (hasPreprocessing() != other.hasPreprocessing()) return false;
    if (hasPreprocessing()) {
      if (!getPreprocessing()
          .equals(other.getPreprocessing())) return false;
    }
    if (hasDecomposition() != other.hasDecomposition()) return false;
    if (hasDecomposition()) {
      if (!getDecomposition()
          .equals(other.getDecomposition())) return false;
    }
    if (hasFinal() != other.hasFinal()) return false;
    if (hasFinal()) {
      if (!getFinal()
          .equals(other.getFinal())) return false;
    }
    if (hasDiagnosticsX13() != other.hasDiagnosticsX13()) return false;
    if (hasDiagnosticsX13()) {
      if (!getDiagnosticsX13()
          .equals(other.getDiagnosticsX13())) return false;
    }
    if (hasDiagnosticsSa() != other.hasDiagnosticsSa()) return false;
    if (hasDiagnosticsSa()) {
      if (!getDiagnosticsSa()
          .equals(other.getDiagnosticsSa())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPreadjustment()) {
      hash = (37 * hash) + PREADJUSTMENT_FIELD_NUMBER;
      hash = (53 * hash) + getPreadjustment().hashCode();
    }
    if (hasPreprocessing()) {
      hash = (37 * hash) + PREPROCESSING_FIELD_NUMBER;
      hash = (53 * hash) + getPreprocessing().hashCode();
    }
    if (hasDecomposition()) {
      hash = (37 * hash) + DECOMPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getDecomposition().hashCode();
    }
    if (hasFinal()) {
      hash = (37 * hash) + FINAL_FIELD_NUMBER;
      hash = (53 * hash) + getFinal().hashCode();
    }
    if (hasDiagnosticsX13()) {
      hash = (37 * hash) + DIAGNOSTICS_X13_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosticsX13().hashCode();
    }
    if (hasDiagnosticsSa()) {
      hash = (37 * hash) + DIAGNOSTICS_SA_FIELD_NUMBER;
      hash = (53 * hash) + getDiagnosticsSa().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jdplus.x13.base.protobuf.X13Results parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jdplus.x13.base.protobuf.X13Results parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.x13.base.protobuf.X13Results parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jdplus.x13.base.protobuf.X13Results prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code x13.X13Results}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:x13.X13Results)
      jdplus.x13.base.protobuf.X13ResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Results_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Results_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jdplus.x13.base.protobuf.X13Results.class, jdplus.x13.base.protobuf.X13Results.Builder.class);
    }

    // Construct using jdplus.x13.base.protobuf.X13Results.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPreadjustmentFieldBuilder();
        internalGetPreprocessingFieldBuilder();
        internalGetDecompositionFieldBuilder();
        internalGetFinalFieldBuilder();
        internalGetDiagnosticsX13FieldBuilder();
        internalGetDiagnosticsSaFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      preadjustment_ = null;
      if (preadjustmentBuilder_ != null) {
        preadjustmentBuilder_.dispose();
        preadjustmentBuilder_ = null;
      }
      preprocessing_ = null;
      if (preprocessingBuilder_ != null) {
        preprocessingBuilder_.dispose();
        preprocessingBuilder_ = null;
      }
      decomposition_ = null;
      if (decompositionBuilder_ != null) {
        decompositionBuilder_.dispose();
        decompositionBuilder_ = null;
      }
      final_ = null;
      if (finalBuilder_ != null) {
        finalBuilder_.dispose();
        finalBuilder_ = null;
      }
      diagnosticsX13_ = null;
      if (diagnosticsX13Builder_ != null) {
        diagnosticsX13Builder_.dispose();
        diagnosticsX13Builder_ = null;
      }
      diagnosticsSa_ = null;
      if (diagnosticsSaBuilder_ != null) {
        diagnosticsSaBuilder_.dispose();
        diagnosticsSaBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jdplus.x13.base.protobuf.X13Protos.internal_static_x13_X13Results_descriptor;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Results getDefaultInstanceForType() {
      return jdplus.x13.base.protobuf.X13Results.getDefaultInstance();
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Results build() {
      jdplus.x13.base.protobuf.X13Results result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jdplus.x13.base.protobuf.X13Results buildPartial() {
      jdplus.x13.base.protobuf.X13Results result = new jdplus.x13.base.protobuf.X13Results(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jdplus.x13.base.protobuf.X13Results result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.preadjustment_ = preadjustmentBuilder_ == null
            ? preadjustment_
            : preadjustmentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.preprocessing_ = preprocessingBuilder_ == null
            ? preprocessing_
            : preprocessingBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.decomposition_ = decompositionBuilder_ == null
            ? decomposition_
            : decompositionBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.final_ = finalBuilder_ == null
            ? final_
            : finalBuilder_.build();
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.diagnosticsX13_ = diagnosticsX13Builder_ == null
            ? diagnosticsX13_
            : diagnosticsX13Builder_.build();
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.diagnosticsSa_ = diagnosticsSaBuilder_ == null
            ? diagnosticsSa_
            : diagnosticsSaBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jdplus.x13.base.protobuf.X13Results) {
        return mergeFrom((jdplus.x13.base.protobuf.X13Results)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jdplus.x13.base.protobuf.X13Results other) {
      if (other == jdplus.x13.base.protobuf.X13Results.getDefaultInstance()) return this;
      if (other.hasPreadjustment()) {
        mergePreadjustment(other.getPreadjustment());
      }
      if (other.hasPreprocessing()) {
        mergePreprocessing(other.getPreprocessing());
      }
      if (other.hasDecomposition()) {
        mergeDecomposition(other.getDecomposition());
      }
      if (other.hasFinal()) {
        mergeFinal(other.getFinal());
      }
      if (other.hasDiagnosticsX13()) {
        mergeDiagnosticsX13(other.getDiagnosticsX13());
      }
      if (other.hasDiagnosticsSa()) {
        mergeDiagnosticsSa(other.getDiagnosticsSa());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetPreadjustmentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPreprocessingFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetDecompositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetFinalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetDiagnosticsX13FieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetDiagnosticsSaFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private jdplus.x13.base.protobuf.X13Preadjustment preadjustment_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X13Preadjustment, jdplus.x13.base.protobuf.X13Preadjustment.Builder, jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder> preadjustmentBuilder_;
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     * @return Whether the preadjustment field is set.
     */
    public boolean hasPreadjustment() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     * @return The preadjustment.
     */
    public jdplus.x13.base.protobuf.X13Preadjustment getPreadjustment() {
      if (preadjustmentBuilder_ == null) {
        return preadjustment_ == null ? jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance() : preadjustment_;
      } else {
        return preadjustmentBuilder_.getMessage();
      }
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public Builder setPreadjustment(jdplus.x13.base.protobuf.X13Preadjustment value) {
      if (preadjustmentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        preadjustment_ = value;
      } else {
        preadjustmentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public Builder setPreadjustment(
        jdplus.x13.base.protobuf.X13Preadjustment.Builder builderForValue) {
      if (preadjustmentBuilder_ == null) {
        preadjustment_ = builderForValue.build();
      } else {
        preadjustmentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public Builder mergePreadjustment(jdplus.x13.base.protobuf.X13Preadjustment value) {
      if (preadjustmentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          preadjustment_ != null &&
          preadjustment_ != jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance()) {
          getPreadjustmentBuilder().mergeFrom(value);
        } else {
          preadjustment_ = value;
        }
      } else {
        preadjustmentBuilder_.mergeFrom(value);
      }
      if (preadjustment_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public Builder clearPreadjustment() {
      bitField0_ = (bitField0_ & ~0x00000001);
      preadjustment_ = null;
      if (preadjustmentBuilder_ != null) {
        preadjustmentBuilder_.dispose();
        preadjustmentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public jdplus.x13.base.protobuf.X13Preadjustment.Builder getPreadjustmentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetPreadjustmentFieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    public jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder getPreadjustmentOrBuilder() {
      if (preadjustmentBuilder_ != null) {
        return preadjustmentBuilder_.getMessageOrBuilder();
      } else {
        return preadjustment_ == null ?
            jdplus.x13.base.protobuf.X13Preadjustment.getDefaultInstance() : preadjustment_;
      }
    }
    /**
     * <code>.x13.X13Preadjustment preadjustment = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X13Preadjustment, jdplus.x13.base.protobuf.X13Preadjustment.Builder, jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder> 
        internalGetPreadjustmentFieldBuilder() {
      if (preadjustmentBuilder_ == null) {
        preadjustmentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.X13Preadjustment, jdplus.x13.base.protobuf.X13Preadjustment.Builder, jdplus.x13.base.protobuf.X13PreadjustmentOrBuilder>(
                getPreadjustment(),
                getParentForChildren(),
                isClean());
        preadjustment_ = null;
      }
      return preadjustmentBuilder_;
    }

    private jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel preprocessing_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.Builder, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder> preprocessingBuilder_;
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     * @return Whether the preprocessing field is set.
     */
    public boolean hasPreprocessing() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     * @return The preprocessing.
     */
    public jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel getPreprocessing() {
      if (preprocessingBuilder_ == null) {
        return preprocessing_ == null ? jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
      } else {
        return preprocessingBuilder_.getMessage();
      }
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public Builder setPreprocessing(jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel value) {
      if (preprocessingBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        preprocessing_ = value;
      } else {
        preprocessingBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public Builder setPreprocessing(
        jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.Builder builderForValue) {
      if (preprocessingBuilder_ == null) {
        preprocessing_ = builderForValue.build();
      } else {
        preprocessingBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public Builder mergePreprocessing(jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel value) {
      if (preprocessingBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          preprocessing_ != null &&
          preprocessing_ != jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.getDefaultInstance()) {
          getPreprocessingBuilder().mergeFrom(value);
        } else {
          preprocessing_ = value;
        }
      } else {
        preprocessingBuilder_.mergeFrom(value);
      }
      if (preprocessing_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public Builder clearPreprocessing() {
      bitField0_ = (bitField0_ & ~0x00000002);
      preprocessing_ = null;
      if (preprocessingBuilder_ != null) {
        preprocessingBuilder_.dispose();
        preprocessingBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.Builder getPreprocessingBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPreprocessingFieldBuilder().getBuilder();
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder getPreprocessingOrBuilder() {
      if (preprocessingBuilder_ != null) {
        return preprocessingBuilder_.getMessageOrBuilder();
      } else {
        return preprocessing_ == null ?
            jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.getDefaultInstance() : preprocessing_;
      }
    }
    /**
     * <code>.regarima.RegArimaModel preprocessing = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.Builder, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder> 
        internalGetPreprocessingFieldBuilder() {
      if (preprocessingBuilder_ == null) {
        preprocessingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel.Builder, jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder>(
                getPreprocessing(),
                getParentForChildren(),
                isClean());
        preprocessing_ = null;
      }
      return preprocessingBuilder_;
    }

    private jdplus.x13.base.protobuf.X11Results decomposition_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X11Results, jdplus.x13.base.protobuf.X11Results.Builder, jdplus.x13.base.protobuf.X11ResultsOrBuilder> decompositionBuilder_;
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     * @return Whether the decomposition field is set.
     */
    public boolean hasDecomposition() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     * @return The decomposition.
     */
    public jdplus.x13.base.protobuf.X11Results getDecomposition() {
      if (decompositionBuilder_ == null) {
        return decomposition_ == null ? jdplus.x13.base.protobuf.X11Results.getDefaultInstance() : decomposition_;
      } else {
        return decompositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public Builder setDecomposition(jdplus.x13.base.protobuf.X11Results value) {
      if (decompositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        decomposition_ = value;
      } else {
        decompositionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public Builder setDecomposition(
        jdplus.x13.base.protobuf.X11Results.Builder builderForValue) {
      if (decompositionBuilder_ == null) {
        decomposition_ = builderForValue.build();
      } else {
        decompositionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public Builder mergeDecomposition(jdplus.x13.base.protobuf.X11Results value) {
      if (decompositionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          decomposition_ != null &&
          decomposition_ != jdplus.x13.base.protobuf.X11Results.getDefaultInstance()) {
          getDecompositionBuilder().mergeFrom(value);
        } else {
          decomposition_ = value;
        }
      } else {
        decompositionBuilder_.mergeFrom(value);
      }
      if (decomposition_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public Builder clearDecomposition() {
      bitField0_ = (bitField0_ & ~0x00000004);
      decomposition_ = null;
      if (decompositionBuilder_ != null) {
        decompositionBuilder_.dispose();
        decompositionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public jdplus.x13.base.protobuf.X11Results.Builder getDecompositionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetDecompositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    public jdplus.x13.base.protobuf.X11ResultsOrBuilder getDecompositionOrBuilder() {
      if (decompositionBuilder_ != null) {
        return decompositionBuilder_.getMessageOrBuilder();
      } else {
        return decomposition_ == null ?
            jdplus.x13.base.protobuf.X11Results.getDefaultInstance() : decomposition_;
      }
    }
    /**
     * <code>.x13.X11Results decomposition = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X11Results, jdplus.x13.base.protobuf.X11Results.Builder, jdplus.x13.base.protobuf.X11ResultsOrBuilder> 
        internalGetDecompositionFieldBuilder() {
      if (decompositionBuilder_ == null) {
        decompositionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.X11Results, jdplus.x13.base.protobuf.X11Results.Builder, jdplus.x13.base.protobuf.X11ResultsOrBuilder>(
                getDecomposition(),
                getParentForChildren(),
                isClean());
        decomposition_ = null;
      }
      return decompositionBuilder_;
    }

    private jdplus.x13.base.protobuf.X13Finals final_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X13Finals, jdplus.x13.base.protobuf.X13Finals.Builder, jdplus.x13.base.protobuf.X13FinalsOrBuilder> finalBuilder_;
    /**
     * <code>.x13.X13Finals final = 4;</code>
     * @return Whether the final field is set.
     */
    public boolean hasFinal() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     * @return The final.
     */
    public jdplus.x13.base.protobuf.X13Finals getFinal() {
      if (finalBuilder_ == null) {
        return final_ == null ? jdplus.x13.base.protobuf.X13Finals.getDefaultInstance() : final_;
      } else {
        return finalBuilder_.getMessage();
      }
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public Builder setFinal(jdplus.x13.base.protobuf.X13Finals value) {
      if (finalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        final_ = value;
      } else {
        finalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public Builder setFinal(
        jdplus.x13.base.protobuf.X13Finals.Builder builderForValue) {
      if (finalBuilder_ == null) {
        final_ = builderForValue.build();
      } else {
        finalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public Builder mergeFinal(jdplus.x13.base.protobuf.X13Finals value) {
      if (finalBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          final_ != null &&
          final_ != jdplus.x13.base.protobuf.X13Finals.getDefaultInstance()) {
          getFinalBuilder().mergeFrom(value);
        } else {
          final_ = value;
        }
      } else {
        finalBuilder_.mergeFrom(value);
      }
      if (final_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public Builder clearFinal() {
      bitField0_ = (bitField0_ & ~0x00000008);
      final_ = null;
      if (finalBuilder_ != null) {
        finalBuilder_.dispose();
        finalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public jdplus.x13.base.protobuf.X13Finals.Builder getFinalBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetFinalFieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    public jdplus.x13.base.protobuf.X13FinalsOrBuilder getFinalOrBuilder() {
      if (finalBuilder_ != null) {
        return finalBuilder_.getMessageOrBuilder();
      } else {
        return final_ == null ?
            jdplus.x13.base.protobuf.X13Finals.getDefaultInstance() : final_;
      }
    }
    /**
     * <code>.x13.X13Finals final = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.X13Finals, jdplus.x13.base.protobuf.X13Finals.Builder, jdplus.x13.base.protobuf.X13FinalsOrBuilder> 
        internalGetFinalFieldBuilder() {
      if (finalBuilder_ == null) {
        finalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.X13Finals, jdplus.x13.base.protobuf.X13Finals.Builder, jdplus.x13.base.protobuf.X13FinalsOrBuilder>(
                getFinal(),
                getParentForChildren(),
                isClean());
        final_ = null;
      }
      return finalBuilder_;
    }

    private jdplus.x13.base.protobuf.Diagnostics diagnosticsX13_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.Diagnostics, jdplus.x13.base.protobuf.Diagnostics.Builder, jdplus.x13.base.protobuf.DiagnosticsOrBuilder> diagnosticsX13Builder_;
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     * @return Whether the diagnosticsX13 field is set.
     */
    public boolean hasDiagnosticsX13() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     * @return The diagnosticsX13.
     */
    public jdplus.x13.base.protobuf.Diagnostics getDiagnosticsX13() {
      if (diagnosticsX13Builder_ == null) {
        return diagnosticsX13_ == null ? jdplus.x13.base.protobuf.Diagnostics.getDefaultInstance() : diagnosticsX13_;
      } else {
        return diagnosticsX13Builder_.getMessage();
      }
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public Builder setDiagnosticsX13(jdplus.x13.base.protobuf.Diagnostics value) {
      if (diagnosticsX13Builder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        diagnosticsX13_ = value;
      } else {
        diagnosticsX13Builder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public Builder setDiagnosticsX13(
        jdplus.x13.base.protobuf.Diagnostics.Builder builderForValue) {
      if (diagnosticsX13Builder_ == null) {
        diagnosticsX13_ = builderForValue.build();
      } else {
        diagnosticsX13Builder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public Builder mergeDiagnosticsX13(jdplus.x13.base.protobuf.Diagnostics value) {
      if (diagnosticsX13Builder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          diagnosticsX13_ != null &&
          diagnosticsX13_ != jdplus.x13.base.protobuf.Diagnostics.getDefaultInstance()) {
          getDiagnosticsX13Builder().mergeFrom(value);
        } else {
          diagnosticsX13_ = value;
        }
      } else {
        diagnosticsX13Builder_.mergeFrom(value);
      }
      if (diagnosticsX13_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public Builder clearDiagnosticsX13() {
      bitField0_ = (bitField0_ & ~0x00000010);
      diagnosticsX13_ = null;
      if (diagnosticsX13Builder_ != null) {
        diagnosticsX13Builder_.dispose();
        diagnosticsX13Builder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public jdplus.x13.base.protobuf.Diagnostics.Builder getDiagnosticsX13Builder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetDiagnosticsX13FieldBuilder().getBuilder();
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    public jdplus.x13.base.protobuf.DiagnosticsOrBuilder getDiagnosticsX13OrBuilder() {
      if (diagnosticsX13Builder_ != null) {
        return diagnosticsX13Builder_.getMessageOrBuilder();
      } else {
        return diagnosticsX13_ == null ?
            jdplus.x13.base.protobuf.Diagnostics.getDefaultInstance() : diagnosticsX13_;
      }
    }
    /**
     * <code>.x13.Diagnostics diagnostics_x13 = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.x13.base.protobuf.Diagnostics, jdplus.x13.base.protobuf.Diagnostics.Builder, jdplus.x13.base.protobuf.DiagnosticsOrBuilder> 
        internalGetDiagnosticsX13FieldBuilder() {
      if (diagnosticsX13Builder_ == null) {
        diagnosticsX13Builder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.x13.base.protobuf.Diagnostics, jdplus.x13.base.protobuf.Diagnostics.Builder, jdplus.x13.base.protobuf.DiagnosticsOrBuilder>(
                getDiagnosticsX13(),
                getParentForChildren(),
                isClean());
        diagnosticsX13_ = null;
      }
      return diagnosticsX13Builder_;
    }

    private jdplus.sa.base.protobuf.SaProtos.Diagnostics diagnosticsSa_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.Diagnostics, jdplus.sa.base.protobuf.SaProtos.Diagnostics.Builder, jdplus.sa.base.protobuf.SaProtos.DiagnosticsOrBuilder> diagnosticsSaBuilder_;
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     * @return Whether the diagnosticsSa field is set.
     */
    public boolean hasDiagnosticsSa() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     * @return The diagnosticsSa.
     */
    public jdplus.sa.base.protobuf.SaProtos.Diagnostics getDiagnosticsSa() {
      if (diagnosticsSaBuilder_ == null) {
        return diagnosticsSa_ == null ? jdplus.sa.base.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
      } else {
        return diagnosticsSaBuilder_.getMessage();
      }
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public Builder setDiagnosticsSa(jdplus.sa.base.protobuf.SaProtos.Diagnostics value) {
      if (diagnosticsSaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        diagnosticsSa_ = value;
      } else {
        diagnosticsSaBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public Builder setDiagnosticsSa(
        jdplus.sa.base.protobuf.SaProtos.Diagnostics.Builder builderForValue) {
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSa_ = builderForValue.build();
      } else {
        diagnosticsSaBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public Builder mergeDiagnosticsSa(jdplus.sa.base.protobuf.SaProtos.Diagnostics value) {
      if (diagnosticsSaBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          diagnosticsSa_ != null &&
          diagnosticsSa_ != jdplus.sa.base.protobuf.SaProtos.Diagnostics.getDefaultInstance()) {
          getDiagnosticsSaBuilder().mergeFrom(value);
        } else {
          diagnosticsSa_ = value;
        }
      } else {
        diagnosticsSaBuilder_.mergeFrom(value);
      }
      if (diagnosticsSa_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public Builder clearDiagnosticsSa() {
      bitField0_ = (bitField0_ & ~0x00000020);
      diagnosticsSa_ = null;
      if (diagnosticsSaBuilder_ != null) {
        diagnosticsSaBuilder_.dispose();
        diagnosticsSaBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.Diagnostics.Builder getDiagnosticsSaBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetDiagnosticsSaFieldBuilder().getBuilder();
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.DiagnosticsOrBuilder getDiagnosticsSaOrBuilder() {
      if (diagnosticsSaBuilder_ != null) {
        return diagnosticsSaBuilder_.getMessageOrBuilder();
      } else {
        return diagnosticsSa_ == null ?
            jdplus.sa.base.protobuf.SaProtos.Diagnostics.getDefaultInstance() : diagnosticsSa_;
      }
    }
    /**
     * <code>.sa.Diagnostics diagnostics_sa = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.Diagnostics, jdplus.sa.base.protobuf.SaProtos.Diagnostics.Builder, jdplus.sa.base.protobuf.SaProtos.DiagnosticsOrBuilder> 
        internalGetDiagnosticsSaFieldBuilder() {
      if (diagnosticsSaBuilder_ == null) {
        diagnosticsSaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.sa.base.protobuf.SaProtos.Diagnostics, jdplus.sa.base.protobuf.SaProtos.Diagnostics.Builder, jdplus.sa.base.protobuf.SaProtos.DiagnosticsOrBuilder>(
                getDiagnosticsSa(),
                getParentForChildren(),
                isClean());
        diagnosticsSa_ = null;
      }
      return diagnosticsSaBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:x13.X13Results)
  }

  // @@protoc_insertion_point(class_scope:x13.X13Results)
  private static final jdplus.x13.base.protobuf.X13Results DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jdplus.x13.base.protobuf.X13Results();
  }

  public static jdplus.x13.base.protobuf.X13Results getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<X13Results>
      PARSER = new com.google.protobuf.AbstractParser<X13Results>() {
    @java.lang.Override
    public X13Results parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<X13Results> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<X13Results> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jdplus.x13.base.protobuf.X13Results getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

