/*
 * Copyright 2026 JDemetra+.
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 *      https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package jdplus.x13.desktop.plugin.x13.ui;

import jdplus.toolkit.base.api.timeseries.Ts;
import jdplus.toolkit.base.api.timeseries.TsDomain;
import jdplus.toolkit.desktop.plugin.ui.processing.TsProcessingViewer;
import jdplus.toolkit.desktop.plugin.ui.properties.l2fprod.UserInterfaceContext;
import jdplus.toolkit.desktop.plugin.workspace.DocumentUIServices;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceFactory;
import jdplus.toolkit.desktop.plugin.workspace.WorkspaceItem;
import jdplus.toolkit.desktop.plugin.workspace.ui.WorkspaceTsTopComponent;
import jdplus.x13.base.api.x13.X13Spec;
import jdplus.x13.base.core.x13.X13Document;
import jdplus.x13.desktop.plugin.x13.documents.X13DocumentManager;
import nbbrd.design.ClassNameConstant;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//demetra.desktop.x13.ui//X13//EN", autostore = false)
@TopComponent.Description(
        preferredID = "X13TopComponent",
        // iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = X13TopComponent.ID)
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1010)
@TopComponent.OpenActionRegistration(displayName = "#CTL_X13Action")
@NbBundle.Messages({"CTL_X13Action=X13", "CTL_X13TopComponent=X13 Window", "HINT_X13TopComponent=This is a X13 window"})
public final class X13TopComponent extends WorkspaceTsTopComponent<X13Document> {

    @ClassNameConstant
    public static final String ID = "jdplus.x13.desktop.plugin.x13.ui.X13TopComponent";

    private final ExplorerManager mgr = new ExplorerManager();

    private static X13DocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(X13DocumentManager.class);
    }

    public X13TopComponent() {
        this(null);
    }

    public X13TopComponent(WorkspaceItem<X13Document> doc) {
        super(doc);
        initComponents();
        setToolTipText(NbBundle.getMessage(X13TopComponent.class, "HINT_X13TopComponent"));
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
    }

    @Override
    public WorkspaceItem<X13Document> newDocument() {
        return manager().create(WorkspaceFactory.getInstance().getActiveWorkspace());
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    @Override
    protected TsProcessingViewer initViewer() {
        return TsProcessingViewer.create(getElement(), DocumentUIServices.forDocument(X13Document.class));
    }

    @Override
    public void componentActivated() {
        super.componentActivated();
        updateUserInterfaceContext();
    }

    @Override
    public void componentDeactivated() {
        super.componentDeactivated();
        UserInterfaceContext.INSTANCE.setAnnualFrequency(0);
    }

    private void updateUserInterfaceContext() {
        if (getDocument() == null) {
            return;
        }
        X13Document element = getElement();
        if (element == null) {
            UserInterfaceContext.INSTANCE.setDomain(null);
        } else {
            X13Spec s = element.getSpecification();
            if (s == null) {
                UserInterfaceContext.INSTANCE.setAnnualFrequency(0);
            } else {
                UserInterfaceContext.INSTANCE.setAnnualFrequency(s.getRegArima().getFrequency());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    } // </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return X13DocumentManager.CONTEXTPATH;
    }

    @Override
    public boolean update(X13Document element, Ts s) {
        if (s != null) {
            TsDomain domain = s.getData().getDomain();
            UserInterfaceContext.INSTANCE.setDomain(domain);
            X13Spec nspec = element.getSpecification().setFrequency(domain.getAnnualFrequency());
            element.set(nspec, s);
        } else {
            UserInterfaceContext.INSTANCE.setDomain(null);
            element.set(s);
        }
        return true;
    }
}
