# gRPC config
quarkus.grpc.server.host=127.0.0.1
%dev.quarkus.grpc.server.port=4566
%prod.quarkus.grpc.server.port=4567
quarkus.grpc.server.enable-reflection-service=true
#quarkus.grpc.server.use-separate-server=false

# OpenAPI config
quarkus.http.host=127.0.0.1
%dev.quarkus.http.port=4568
%prod.quarkus.http.port=4569
quarkus.swagger-ui.always-include=true
mp.openapi.scan.exclude.packages=com.google.protobuf

# Native config
quarkus.native.auto-service-loader-registration=true

# CORS config
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=/http://localhost:.*/,/http://127\.0\.0\.1:.*/,null
#quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-max-age=24H
