// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: tramoseats.proto
// Protobuf Java Version: 4.30.2

package jdplus.tramoseats.base.protobuf;

/**
 * Protobuf type {@code tramoseats.SeatsResults}
 */
public final class SeatsResults extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:tramoseats.SeatsResults)
    SeatsResultsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 30,
      /* patch= */ 2,
      /* suffix= */ "",
      SeatsResults.class.getName());
  }
  // Use SeatsResults.newBuilder() to construct.
  private SeatsResults(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SeatsResults() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jdplus.tramoseats.base.protobuf.TramoSeatsProtos.internal_static_tramoseats_SeatsResults_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jdplus.tramoseats.base.protobuf.TramoSeatsProtos.internal_static_tramoseats_SeatsResults_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jdplus.tramoseats.base.protobuf.SeatsResults.class, jdplus.tramoseats.base.protobuf.SeatsResults.Builder.class);
  }

  private int bitField0_;
  private int modelCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object model_;
  public enum ModelCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    SEATS_ARIMA(1),
    SEATS_SARIMA(2),
    MODEL_NOT_SET(0);
    private final int value;
    private ModelCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ModelCase valueOf(int value) {
      return forNumber(value);
    }

    public static ModelCase forNumber(int value) {
      switch (value) {
        case 1: return SEATS_ARIMA;
        case 2: return SEATS_SARIMA;
        case 0: return MODEL_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ModelCase
  getModelCase() {
    return ModelCase.forNumber(
        modelCase_);
  }

  public static final int SEATS_ARIMA_FIELD_NUMBER = 1;
  /**
   * <code>.modelling.ArimaModel seats_arima = 1;</code>
   * @return Whether the seatsArima field is set.
   */
  @java.lang.Override
  public boolean hasSeatsArima() {
    return modelCase_ == 1;
  }
  /**
   * <code>.modelling.ArimaModel seats_arima = 1;</code>
   * @return The seatsArima.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel getSeatsArima() {
    if (modelCase_ == 1) {
       return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_;
    }
    return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
  }
  /**
   * <code>.modelling.ArimaModel seats_arima = 1;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModelOrBuilder getSeatsArimaOrBuilder() {
    if (modelCase_ == 1) {
       return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_;
    }
    return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
  }

  public static final int SEATS_SARIMA_FIELD_NUMBER = 2;
  /**
   * <code>.modelling.SarimaModel seats_sarima = 2;</code>
   * @return Whether the seatsSarima field is set.
   */
  @java.lang.Override
  public boolean hasSeatsSarima() {
    return modelCase_ == 2;
  }
  /**
   * <code>.modelling.SarimaModel seats_sarima = 2;</code>
   * @return The seatsSarima.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel getSeatsSarima() {
    if (modelCase_ == 2) {
       return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_;
    }
    return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
  }
  /**
   * <code>.modelling.SarimaModel seats_sarima = 2;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModelOrBuilder getSeatsSarimaOrBuilder() {
    if (modelCase_ == 2) {
       return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_;
    }
    return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
  }

  public static final int MEAN_FIELD_NUMBER = 3;
  private boolean mean_ = false;
  /**
   * <code>bool mean = 3;</code>
   * @return The mean.
   */
  @java.lang.Override
  public boolean getMean() {
    return mean_;
  }

  public static final int CANONICAL_DECOMPOSITION_FIELD_NUMBER = 4;
  private jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel canonicalDecomposition_;
  /**
   * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
   * @return Whether the canonicalDecomposition field is set.
   */
  @java.lang.Override
  public boolean hasCanonicalDecomposition() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
   * @return The canonicalDecomposition.
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel getCanonicalDecomposition() {
    return canonicalDecomposition_ == null ? jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.getDefaultInstance() : canonicalDecomposition_;
  }
  /**
   * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
   */
  @java.lang.Override
  public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModelOrBuilder getCanonicalDecompositionOrBuilder() {
    return canonicalDecomposition_ == null ? jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.getDefaultInstance() : canonicalDecomposition_;
  }

  public static final int STOCHASTICS_FIELD_NUMBER = 5;
  private jdplus.sa.base.protobuf.SaProtos.SaDecomposition stochastics_;
  /**
   * <code>.sa.SaDecomposition stochastics = 5;</code>
   * @return Whether the stochastics field is set.
   */
  @java.lang.Override
  public boolean hasStochastics() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.sa.SaDecomposition stochastics = 5;</code>
   * @return The stochastics.
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.SaDecomposition getStochastics() {
    return stochastics_ == null ? jdplus.sa.base.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : stochastics_;
  }
  /**
   * <code>.sa.SaDecomposition stochastics = 5;</code>
   */
  @java.lang.Override
  public jdplus.sa.base.protobuf.SaProtos.SaDecompositionOrBuilder getStochasticsOrBuilder() {
    return stochastics_ == null ? jdplus.sa.base.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : stochastics_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (modelCase_ == 1) {
      output.writeMessage(1, (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_);
    }
    if (modelCase_ == 2) {
      output.writeMessage(2, (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_);
    }
    if (mean_ != false) {
      output.writeBool(3, mean_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(4, getCanonicalDecomposition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getStochastics());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (modelCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_);
    }
    if (modelCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_);
    }
    if (mean_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, mean_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCanonicalDecomposition());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getStochastics());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jdplus.tramoseats.base.protobuf.SeatsResults)) {
      return super.equals(obj);
    }
    jdplus.tramoseats.base.protobuf.SeatsResults other = (jdplus.tramoseats.base.protobuf.SeatsResults) obj;

    if (getMean()
        != other.getMean()) return false;
    if (hasCanonicalDecomposition() != other.hasCanonicalDecomposition()) return false;
    if (hasCanonicalDecomposition()) {
      if (!getCanonicalDecomposition()
          .equals(other.getCanonicalDecomposition())) return false;
    }
    if (hasStochastics() != other.hasStochastics()) return false;
    if (hasStochastics()) {
      if (!getStochastics()
          .equals(other.getStochastics())) return false;
    }
    if (!getModelCase().equals(other.getModelCase())) return false;
    switch (modelCase_) {
      case 1:
        if (!getSeatsArima()
            .equals(other.getSeatsArima())) return false;
        break;
      case 2:
        if (!getSeatsSarima()
            .equals(other.getSeatsSarima())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEAN_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMean());
    if (hasCanonicalDecomposition()) {
      hash = (37 * hash) + CANONICAL_DECOMPOSITION_FIELD_NUMBER;
      hash = (53 * hash) + getCanonicalDecomposition().hashCode();
    }
    if (hasStochastics()) {
      hash = (37 * hash) + STOCHASTICS_FIELD_NUMBER;
      hash = (53 * hash) + getStochastics().hashCode();
    }
    switch (modelCase_) {
      case 1:
        hash = (37 * hash) + SEATS_ARIMA_FIELD_NUMBER;
        hash = (53 * hash) + getSeatsArima().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SEATS_SARIMA_FIELD_NUMBER;
        hash = (53 * hash) + getSeatsSarima().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jdplus.tramoseats.base.protobuf.SeatsResults parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jdplus.tramoseats.base.protobuf.SeatsResults parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jdplus.tramoseats.base.protobuf.SeatsResults parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jdplus.tramoseats.base.protobuf.SeatsResults prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code tramoseats.SeatsResults}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:tramoseats.SeatsResults)
      jdplus.tramoseats.base.protobuf.SeatsResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jdplus.tramoseats.base.protobuf.TramoSeatsProtos.internal_static_tramoseats_SeatsResults_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jdplus.tramoseats.base.protobuf.TramoSeatsProtos.internal_static_tramoseats_SeatsResults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jdplus.tramoseats.base.protobuf.SeatsResults.class, jdplus.tramoseats.base.protobuf.SeatsResults.Builder.class);
    }

    // Construct using jdplus.tramoseats.base.protobuf.SeatsResults.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCanonicalDecompositionFieldBuilder();
        internalGetStochasticsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (seatsArimaBuilder_ != null) {
        seatsArimaBuilder_.clear();
      }
      if (seatsSarimaBuilder_ != null) {
        seatsSarimaBuilder_.clear();
      }
      mean_ = false;
      canonicalDecomposition_ = null;
      if (canonicalDecompositionBuilder_ != null) {
        canonicalDecompositionBuilder_.dispose();
        canonicalDecompositionBuilder_ = null;
      }
      stochastics_ = null;
      if (stochasticsBuilder_ != null) {
        stochasticsBuilder_.dispose();
        stochasticsBuilder_ = null;
      }
      modelCase_ = 0;
      model_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jdplus.tramoseats.base.protobuf.TramoSeatsProtos.internal_static_tramoseats_SeatsResults_descriptor;
    }

    @java.lang.Override
    public jdplus.tramoseats.base.protobuf.SeatsResults getDefaultInstanceForType() {
      return jdplus.tramoseats.base.protobuf.SeatsResults.getDefaultInstance();
    }

    @java.lang.Override
    public jdplus.tramoseats.base.protobuf.SeatsResults build() {
      jdplus.tramoseats.base.protobuf.SeatsResults result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jdplus.tramoseats.base.protobuf.SeatsResults buildPartial() {
      jdplus.tramoseats.base.protobuf.SeatsResults result = new jdplus.tramoseats.base.protobuf.SeatsResults(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(jdplus.tramoseats.base.protobuf.SeatsResults result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.mean_ = mean_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.canonicalDecomposition_ = canonicalDecompositionBuilder_ == null
            ? canonicalDecomposition_
            : canonicalDecompositionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.stochastics_ = stochasticsBuilder_ == null
            ? stochastics_
            : stochasticsBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(jdplus.tramoseats.base.protobuf.SeatsResults result) {
      result.modelCase_ = modelCase_;
      result.model_ = this.model_;
      if (modelCase_ == 1 &&
          seatsArimaBuilder_ != null) {
        result.model_ = seatsArimaBuilder_.build();
      }
      if (modelCase_ == 2 &&
          seatsSarimaBuilder_ != null) {
        result.model_ = seatsSarimaBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jdplus.tramoseats.base.protobuf.SeatsResults) {
        return mergeFrom((jdplus.tramoseats.base.protobuf.SeatsResults)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jdplus.tramoseats.base.protobuf.SeatsResults other) {
      if (other == jdplus.tramoseats.base.protobuf.SeatsResults.getDefaultInstance()) return this;
      if (other.getMean() != false) {
        setMean(other.getMean());
      }
      if (other.hasCanonicalDecomposition()) {
        mergeCanonicalDecomposition(other.getCanonicalDecomposition());
      }
      if (other.hasStochastics()) {
        mergeStochastics(other.getStochastics());
      }
      switch (other.getModelCase()) {
        case SEATS_ARIMA: {
          mergeSeatsArima(other.getSeatsArima());
          break;
        }
        case SEATS_SARIMA: {
          mergeSeatsSarima(other.getSeatsSarima());
          break;
        }
        case MODEL_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetSeatsArimaFieldBuilder().getBuilder(),
                  extensionRegistry);
              modelCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetSeatsSarimaFieldBuilder().getBuilder(),
                  extensionRegistry);
              modelCase_ = 2;
              break;
            } // case 18
            case 24: {
              mean_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              input.readMessage(
                  internalGetCanonicalDecompositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetStochasticsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int modelCase_ = 0;
    private java.lang.Object model_;
    public ModelCase
        getModelCase() {
      return ModelCase.forNumber(
          modelCase_);
    }

    public Builder clearModel() {
      modelCase_ = 0;
      model_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModelOrBuilder> seatsArimaBuilder_;
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     * @return Whether the seatsArima field is set.
     */
    @java.lang.Override
    public boolean hasSeatsArima() {
      return modelCase_ == 1;
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     * @return The seatsArima.
     */
    @java.lang.Override
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel getSeatsArima() {
      if (seatsArimaBuilder_ == null) {
        if (modelCase_ == 1) {
          return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_;
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
      } else {
        if (modelCase_ == 1) {
          return seatsArimaBuilder_.getMessage();
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
      }
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    public Builder setSeatsArima(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel value) {
      if (seatsArimaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        model_ = value;
        onChanged();
      } else {
        seatsArimaBuilder_.setMessage(value);
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    public Builder setSeatsArima(
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.Builder builderForValue) {
      if (seatsArimaBuilder_ == null) {
        model_ = builderForValue.build();
        onChanged();
      } else {
        seatsArimaBuilder_.setMessage(builderForValue.build());
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    public Builder mergeSeatsArima(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel value) {
      if (seatsArimaBuilder_ == null) {
        if (modelCase_ == 1 &&
            model_ != jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance()) {
          model_ = jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.newBuilder((jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_)
              .mergeFrom(value).buildPartial();
        } else {
          model_ = value;
        }
        onChanged();
      } else {
        if (modelCase_ == 1) {
          seatsArimaBuilder_.mergeFrom(value);
        } else {
          seatsArimaBuilder_.setMessage(value);
        }
      }
      modelCase_ = 1;
      return this;
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    public Builder clearSeatsArima() {
      if (seatsArimaBuilder_ == null) {
        if (modelCase_ == 1) {
          modelCase_ = 0;
          model_ = null;
          onChanged();
        }
      } else {
        if (modelCase_ == 1) {
          modelCase_ = 0;
          model_ = null;
        }
        seatsArimaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.Builder getSeatsArimaBuilder() {
      return internalGetSeatsArimaFieldBuilder().getBuilder();
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    @java.lang.Override
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModelOrBuilder getSeatsArimaOrBuilder() {
      if ((modelCase_ == 1) && (seatsArimaBuilder_ != null)) {
        return seatsArimaBuilder_.getMessageOrBuilder();
      } else {
        if (modelCase_ == 1) {
          return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_;
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
      }
    }
    /**
     * <code>.modelling.ArimaModel seats_arima = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModelOrBuilder> 
        internalGetSeatsArimaFieldBuilder() {
      if (seatsArimaBuilder_ == null) {
        if (!(modelCase_ == 1)) {
          model_ = jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.getDefaultInstance();
        }
        seatsArimaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModelOrBuilder>(
                (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.ArimaModel) model_,
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      modelCase_ = 1;
      onChanged();
      return seatsArimaBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModelOrBuilder> seatsSarimaBuilder_;
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     * @return Whether the seatsSarima field is set.
     */
    @java.lang.Override
    public boolean hasSeatsSarima() {
      return modelCase_ == 2;
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     * @return The seatsSarima.
     */
    @java.lang.Override
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel getSeatsSarima() {
      if (seatsSarimaBuilder_ == null) {
        if (modelCase_ == 2) {
          return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_;
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
      } else {
        if (modelCase_ == 2) {
          return seatsSarimaBuilder_.getMessage();
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
      }
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    public Builder setSeatsSarima(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel value) {
      if (seatsSarimaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        model_ = value;
        onChanged();
      } else {
        seatsSarimaBuilder_.setMessage(value);
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    public Builder setSeatsSarima(
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.Builder builderForValue) {
      if (seatsSarimaBuilder_ == null) {
        model_ = builderForValue.build();
        onChanged();
      } else {
        seatsSarimaBuilder_.setMessage(builderForValue.build());
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    public Builder mergeSeatsSarima(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel value) {
      if (seatsSarimaBuilder_ == null) {
        if (modelCase_ == 2 &&
            model_ != jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance()) {
          model_ = jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.newBuilder((jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_)
              .mergeFrom(value).buildPartial();
        } else {
          model_ = value;
        }
        onChanged();
      } else {
        if (modelCase_ == 2) {
          seatsSarimaBuilder_.mergeFrom(value);
        } else {
          seatsSarimaBuilder_.setMessage(value);
        }
      }
      modelCase_ = 2;
      return this;
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    public Builder clearSeatsSarima() {
      if (seatsSarimaBuilder_ == null) {
        if (modelCase_ == 2) {
          modelCase_ = 0;
          model_ = null;
          onChanged();
        }
      } else {
        if (modelCase_ == 2) {
          modelCase_ = 0;
          model_ = null;
        }
        seatsSarimaBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.Builder getSeatsSarimaBuilder() {
      return internalGetSeatsSarimaFieldBuilder().getBuilder();
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    @java.lang.Override
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModelOrBuilder getSeatsSarimaOrBuilder() {
      if ((modelCase_ == 2) && (seatsSarimaBuilder_ != null)) {
        return seatsSarimaBuilder_.getMessageOrBuilder();
      } else {
        if (modelCase_ == 2) {
          return (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_;
        }
        return jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
      }
    }
    /**
     * <code>.modelling.SarimaModel seats_sarima = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModelOrBuilder> 
        internalGetSeatsSarimaFieldBuilder() {
      if (seatsSarimaBuilder_ == null) {
        if (!(modelCase_ == 2)) {
          model_ = jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.getDefaultInstance();
        }
        seatsSarimaBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModelOrBuilder>(
                (jdplus.toolkit.base.protobuf.modelling.ModellingProtos.SarimaModel) model_,
                getParentForChildren(),
                isClean());
        model_ = null;
      }
      modelCase_ = 2;
      onChanged();
      return seatsSarimaBuilder_;
    }

    private boolean mean_ ;
    /**
     * <code>bool mean = 3;</code>
     * @return The mean.
     */
    @java.lang.Override
    public boolean getMean() {
      return mean_;
    }
    /**
     * <code>bool mean = 3;</code>
     * @param value The mean to set.
     * @return This builder for chaining.
     */
    public Builder setMean(boolean value) {

      mean_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool mean = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMean() {
      bitField0_ = (bitField0_ & ~0x00000004);
      mean_ = false;
      onChanged();
      return this;
    }

    private jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel canonicalDecomposition_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModelOrBuilder> canonicalDecompositionBuilder_;
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     * @return Whether the canonicalDecomposition field is set.
     */
    public boolean hasCanonicalDecomposition() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     * @return The canonicalDecomposition.
     */
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel getCanonicalDecomposition() {
      if (canonicalDecompositionBuilder_ == null) {
        return canonicalDecomposition_ == null ? jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.getDefaultInstance() : canonicalDecomposition_;
      } else {
        return canonicalDecompositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public Builder setCanonicalDecomposition(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel value) {
      if (canonicalDecompositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        canonicalDecomposition_ = value;
      } else {
        canonicalDecompositionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public Builder setCanonicalDecomposition(
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.Builder builderForValue) {
      if (canonicalDecompositionBuilder_ == null) {
        canonicalDecomposition_ = builderForValue.build();
      } else {
        canonicalDecompositionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public Builder mergeCanonicalDecomposition(jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel value) {
      if (canonicalDecompositionBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          canonicalDecomposition_ != null &&
          canonicalDecomposition_ != jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.getDefaultInstance()) {
          getCanonicalDecompositionBuilder().mergeFrom(value);
        } else {
          canonicalDecomposition_ = value;
        }
      } else {
        canonicalDecompositionBuilder_.mergeFrom(value);
      }
      if (canonicalDecomposition_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public Builder clearCanonicalDecomposition() {
      bitField0_ = (bitField0_ & ~0x00000008);
      canonicalDecomposition_ = null;
      if (canonicalDecompositionBuilder_ != null) {
        canonicalDecompositionBuilder_.dispose();
        canonicalDecompositionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.Builder getCanonicalDecompositionBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetCanonicalDecompositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    public jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModelOrBuilder getCanonicalDecompositionOrBuilder() {
      if (canonicalDecompositionBuilder_ != null) {
        return canonicalDecompositionBuilder_.getMessageOrBuilder();
      } else {
        return canonicalDecomposition_ == null ?
            jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.getDefaultInstance() : canonicalDecomposition_;
      }
    }
    /**
     * <code>.modelling.UcarimaModel canonical_decomposition = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModelOrBuilder> 
        internalGetCanonicalDecompositionFieldBuilder() {
      if (canonicalDecompositionBuilder_ == null) {
        canonicalDecompositionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModel.Builder, jdplus.toolkit.base.protobuf.modelling.ModellingProtos.UcarimaModelOrBuilder>(
                getCanonicalDecomposition(),
                getParentForChildren(),
                isClean());
        canonicalDecomposition_ = null;
      }
      return canonicalDecompositionBuilder_;
    }

    private jdplus.sa.base.protobuf.SaProtos.SaDecomposition stochastics_;
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.SaDecomposition, jdplus.sa.base.protobuf.SaProtos.SaDecomposition.Builder, jdplus.sa.base.protobuf.SaProtos.SaDecompositionOrBuilder> stochasticsBuilder_;
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     * @return Whether the stochastics field is set.
     */
    public boolean hasStochastics() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     * @return The stochastics.
     */
    public jdplus.sa.base.protobuf.SaProtos.SaDecomposition getStochastics() {
      if (stochasticsBuilder_ == null) {
        return stochastics_ == null ? jdplus.sa.base.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : stochastics_;
      } else {
        return stochasticsBuilder_.getMessage();
      }
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public Builder setStochastics(jdplus.sa.base.protobuf.SaProtos.SaDecomposition value) {
      if (stochasticsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stochastics_ = value;
      } else {
        stochasticsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public Builder setStochastics(
        jdplus.sa.base.protobuf.SaProtos.SaDecomposition.Builder builderForValue) {
      if (stochasticsBuilder_ == null) {
        stochastics_ = builderForValue.build();
      } else {
        stochasticsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public Builder mergeStochastics(jdplus.sa.base.protobuf.SaProtos.SaDecomposition value) {
      if (stochasticsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          stochastics_ != null &&
          stochastics_ != jdplus.sa.base.protobuf.SaProtos.SaDecomposition.getDefaultInstance()) {
          getStochasticsBuilder().mergeFrom(value);
        } else {
          stochastics_ = value;
        }
      } else {
        stochasticsBuilder_.mergeFrom(value);
      }
      if (stochastics_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public Builder clearStochastics() {
      bitField0_ = (bitField0_ & ~0x00000010);
      stochastics_ = null;
      if (stochasticsBuilder_ != null) {
        stochasticsBuilder_.dispose();
        stochasticsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.SaDecomposition.Builder getStochasticsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetStochasticsFieldBuilder().getBuilder();
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    public jdplus.sa.base.protobuf.SaProtos.SaDecompositionOrBuilder getStochasticsOrBuilder() {
      if (stochasticsBuilder_ != null) {
        return stochasticsBuilder_.getMessageOrBuilder();
      } else {
        return stochastics_ == null ?
            jdplus.sa.base.protobuf.SaProtos.SaDecomposition.getDefaultInstance() : stochastics_;
      }
    }
    /**
     * <code>.sa.SaDecomposition stochastics = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jdplus.sa.base.protobuf.SaProtos.SaDecomposition, jdplus.sa.base.protobuf.SaProtos.SaDecomposition.Builder, jdplus.sa.base.protobuf.SaProtos.SaDecompositionOrBuilder> 
        internalGetStochasticsFieldBuilder() {
      if (stochasticsBuilder_ == null) {
        stochasticsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jdplus.sa.base.protobuf.SaProtos.SaDecomposition, jdplus.sa.base.protobuf.SaProtos.SaDecomposition.Builder, jdplus.sa.base.protobuf.SaProtos.SaDecompositionOrBuilder>(
                getStochastics(),
                getParentForChildren(),
                isClean());
        stochastics_ = null;
      }
      return stochasticsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:tramoseats.SeatsResults)
  }

  // @@protoc_insertion_point(class_scope:tramoseats.SeatsResults)
  private static final jdplus.tramoseats.base.protobuf.SeatsResults DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jdplus.tramoseats.base.protobuf.SeatsResults();
  }

  public static jdplus.tramoseats.base.protobuf.SeatsResults getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SeatsResults>
      PARSER = new com.google.protobuf.AbstractParser<SeatsResults>() {
    @java.lang.Override
    public SeatsResults parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SeatsResults> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SeatsResults> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jdplus.tramoseats.base.protobuf.SeatsResults getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

