// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tramoseats.proto

package jdplus.tramoseats.base.protobuf;

import jdplus.sa.base.protobuf.SaProtos;

public interface TramoSeatsResultsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tramoseats.TramoSeatsResults)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   * @return Whether the preprocessing field is set.
   */
  boolean hasPreprocessing();
  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   * @return The preprocessing.
   */
  jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModel getPreprocessing();
  /**
   * <code>.regarima.RegArimaModel preprocessing = 1;</code>
   */
  jdplus.toolkit.base.protobuf.regarima.RegArimaProtos.RegArimaModelOrBuilder getPreprocessingOrBuilder();

  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   * @return Whether the decomposition field is set.
   */
  boolean hasDecomposition();
  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   * @return The decomposition.
   */
  SeatsResults getDecomposition();
  /**
   * <code>.tramoseats.SeatsResults decomposition = 2;</code>
   */
  SeatsResultsOrBuilder getDecompositionOrBuilder();

  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   * @return Whether the final field is set.
   */
  boolean hasFinal();
  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   * @return The final.
   */
  SaProtos.SaDecomposition getFinal();
  /**
   * <code>.sa.SaDecomposition final = 3;</code>
   */
  SaProtos.SaDecompositionOrBuilder getFinalOrBuilder();

  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   * @return Whether the diagnosticsSa field is set.
   */
  boolean hasDiagnosticsSa();
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   * @return The diagnosticsSa.
   */
  SaProtos.Diagnostics getDiagnosticsSa();
  /**
   * <code>.sa.Diagnostics diagnostics_sa = 5;</code>
   */
  SaProtos.DiagnosticsOrBuilder getDiagnosticsSaOrBuilder();
}
